#!/usr/bin/env python

#   standard
import cgi, cgitb
from datetime import datetime
import os

#   custom
import admin
import login
import html
from session import Session
from utils import load_settings, mdb, get_logger, record_response_time


if __name__ == "__main__":

    start = datetime.now()

    settings = load_settings()
    logger = get_logger()
    if settings.getboolean("application","debug"):
        cgitb.enable()

    params = cgi.FieldStorage()

    try:
        S = Session(params)
    except Exception as e:
        logger.critical("Caught exception while creating session!")
        logger.exception(e)
        raise

    if S.session is None:
        output = login.render()
    else:
        S.process_params(user_action="viewing %s" % S.get_current_view())
        if "norefresh" in params and S.session is not None:
            print html.meta.norefresh_response.safe_substitute(response="OK",status=200)
        else:
            output, body = S.current_view_html()

    stop = datetime.now()
    record_response_time(S.get_current_view(), stop-start)

    if "norefresh" not in params:
        ui_templates = ['nav.html', 'new_survivor.html','report_error.html']
        html.render(output, body_class=body, session_object=S, include_templates = ui_templates)
