#!/usr/bin/env python

#   standard
import cgi, cgitb
import os

#   custom
import admin
import html
from session import Session
from utils import load_settings, mdb, get_logger


if __name__ == "__main__":
    settings = load_settings()
    logger = get_logger()
    if settings.getboolean("application","DEBUG"):
        cgitb.enable()

    output = html.login.form
    body = "sign_in"

    params = cgi.FieldStorage()

    try:
        S = Session(params)
    except Exception as e:
        logger.critical("Caught exception while creating session!")
        logger.exception(e)
        raise

    if S.session is None and "recover_password" not in params:
        output = html.authenticate_by_form(params)
    elif S.session is None and "recover_password" in params:
        output = S.recover_password()
    else:
        S.process_params(user_action="viewing %s" % S.session["current_view"])
        try:
            output, body = S.current_view_html()
        except TypeError:
            msg = "Caught exception while rendering index!"
            logger.critical(msg)
            output = "Could not create '%s' view for '%s' (session: %s)" % (S.session["current_view"], S.User.user["login"], S.session["_id"])

    html.render(output, body_class=body, session_object=S)
