#!/usr/bin/env python

#   standard
import cgi, cgitb
from datetime import datetime
import os

#   app modules
import admin
import login
import html
from session import Session
import socket
import sys
import utils


if __name__ == "__main__":

    start = datetime.now()

    settings = utils.load_settings()
#    logger = utils.get_logger()

    # CGI application initialization
    if settings.getboolean("application","debug"):
        cgitb.enable()
    params = cgi.FieldStorage()

    # initialize a session and render some HTML
    S = Session(params)
    if S.session is None:
        current_view = "login"
        output = login.render()
    else:
        S.process_params()
        current_view = S.current_view
        output, body = S.current_view_html()

        # set the head
        head = []
        if S.set_cookie:
            head.append(S.AuthObject.set_cookie_js(S.session["_id"], S.session["access_token"]))

        # render!
        html.render(output, body_class=body, head=head)


    stop = datetime.now()
    utils.record_response_time(current_view, stop-start)

    sys.exit(0)
