#!/bin/bash

### BEGIN INIT INFO
# Provides:             kdm-manager
# Required-Start:       $local_fs $remote_fs $network $syslog $named
# Required-Stop:        $local_fs $remote_fs $network $syslog $named
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    starts the CGI application server
# Description:          starts the CGI application server
### END INIT INFO

