#!/usr/bin/python2.7

core = [
    "Beacon",
    "Black Rock",
    "Black Friday",
    "Blackwalk",
    "Bloodreach",
    "Bloodstone",
    "Bloodwalk",
    "Darkreach",
    "Deadrock",
    "Death Heim",
    "Death Mountain",
    "Death Wood",
    "Doomrock",
    "Dreadrock",
    "Ember",
    "First Light",
    "Founder's Rest",
    "Gormrange",
    "Haven",
    "Home",
    "Hope",
    "Hyrule",
    "Lantern's Reach",
    "Last Light",
    "Lightfall",
    "Lux",
    "Nox",
    "Sanctuary",
    "Satan's Lantern",
    "Stonemarch",
    "The Ancient Lantern",
    "The Black Lantern",
    "The Gambler's Lantern",
    "The Gold Lantern",
    "The Silver Lantern",
    "The White Lantern",
#    "Tyndall",
    "White Rock",
    "Witchweed",
]
