#!/usr/bin/python2.7

core = [
    "Anor Londo",
    "Beacon",
    "Blackrock",
    "Blackwalk",
    "Bleakstone",
    "Bloodreach",
    "Bloodstone",
    "Bloodwalk",
    "Darkreach",
    "Darill's Tomb",
    "Darunia",
    "Deadrock",
    "Death Heim",
    "Death Mountain",
    "Doomrock",
    "Dreadrock",
    "Eastmost Penninsula",
    "Ember",
    "Fabul",
    "First Light",
    "Founder's Rest",
    "Gormrange",
    "Graverock",
    "Gravestone",
    "Haven",
    "Home",
    "Hope",
    "Hyrule",
    "Izalith",
    "Kaer Morhen"
    "Kasuto",
    "Kattegat",
    "Lantern's Reach",
    "Last Light",
    "Lightfall",
    "Lufenia",
    "Lux",
    "Melmond",
    "Mido",
    "Mist",
    "Mysidia",
    "Narshe",
    "Nilfgaard",
    "Nox",
    "Old Kasuto",
    "Onrac",
    "Rivia",
    "Ruto",
    "Sanctuary",
    "Satan's Lantern",
    "Spectacle Rock",
    "Stonemarch",
    "The Ancient Lantern",
    "The Black Lantern",
    "The Gambler's Lantern",
    "The Gold Lantern",
    "The Silver Lantern",
    "The White Lantern",
    "Three Eye Rock",
    "Vizima",
    "White Rock",
    "Witchweed",
]
