#!/usr/bin/python2.7

core = [
    "Beacon",
    "Black Rock",
    "Black Friday",
    "Blackwalk",
    "Bloodreach",
    "Bloodstone",
    "Bloodwalk",
    "Darkreach",
    "Darill's Tomb",
    "Darunia",
    "Deadrock",
    "Death Heim",
    "Death Mountain",
    "Death Wood",
    "Doomrock",
    "Dreadrock",
    "Eastmost Penninsula",
    "Ember",
    "Fabul",
    "First Light",
    "Founder's Rest",
    "Gormrange",
    "Haven",
    "Home",
    "Hope",
    "Hyrule",
    "Kasuto",
    "Lantern's Reach",
    "Last Light",
    "Lightfall",
    "Lufenia",
    "Lux",
    "Melmond",
    "Mido",
    "Mist",
    "Mysidia",
    "Narshe",
    "Nox",
    "Old Kasuto",
    "Onrac",
    "Ruto",
    "Sanctuary",
    "Satan's Lantern",
    "Spectacle Rock",
    "Stonemarch",
    "The Ancient Lantern",
    "The Black Lantern",
    "The Gambler's Lantern",
    "The Gold Lantern",
    "The Silver Lantern",
    "The White Lantern",
    "Three Eye Rock",
#    "Tyndall",
    "White Rock",
    "Witchweed",
]
