mar_2016_expansions = {

    # Dragon King 
    'approached_the_throne': {
        'name': 'Approached the Throne',
        'expansion': 'dragon_king',
    },
    'atomic_heart': {'expansion': 'dragon_king', 'name': 'Atomic Heart'},
    'consumer_of_lies': {'expansion': 'dragon_king', 'name': 'Consumer of Lies'},
    'consumer_of_sins': {'expansion': 'dragon_king', 'name': 'Consumer of Sins'},
    'dragonkin': {'expansion': 'dragon_king', 'name': 'Dragonkin'},
    'foundling': {
        'name': 'Foundling',
        'bgcolor': 'FFC107',
        'bordercolor': 'FFC107',
        'expansion': 'dragon_king',
    },
    'gladiator': {'expansion': 'dragon_king', 'name': 'Gladiator'},
    'held_the_radiant_heart': {
        'name': 'Held the Radiant Heart',
        'expansion': 'dragon_king',
    },
    'husk': {'expansion': 'dragon_king', 'name': 'Husk'},
    'imago_tyrannis': {'expansion': 'dragon_king', 'name': 'Imago Tyrannis'},
    'molded_by_the_tyrant': {'expansion': 'dragon_king', 'name': 'Molded by the Tyrant'},
    'noble': {'expansion': 'dragon_king', 'name': 'Noble'},
    'nuclear_warrior': {'expansion': 'dragon_king', 'name': 'Nuclear Warrior'},
    'numerologist': {'expansion': 'dragon_king', 'name': 'Numerologist'},
    'peered_into_destiny': {'expansion': 'dragon_king','name': 'Peered into Destiny'},
    "pristine": {'expansion': 'dragon_king', 'name': 'Pristine'},
    'reincarnated': {'expansion': 'dragon_king', 'name': 'Reincarnated'},
    'star_gazer': {'expansion': 'dragon_king', 'name': 'Star Gazer'},
    'starbound': {'expansion': 'dragon_king', 'name': 'Starbound'},
    'successor': {'expansion': 'dragon_king', 'name': 'Successor'},
    'sweetmeat_eater': {'expansion': 'dragon_king', 'name': 'Sweetmeat Eater'},
    'the_absolute': {
        'name': 'The Absolute',
        'bgcolor': '4527A0',
        'bordercolor': '4527A0',
        'color': 'FFF',
        'expansion': 'dragon_king',
        'selectable': False,
    },
    'the_gambler': {
        'name': 'The Gambler',
        'bgcolor': '4527A0',
        'bordercolor': '4527A0',
        'color': 'FFF',
        'expansion': 'dragon_king',
        'selectable': False,
    },
    'the_goblin': {
        'bgcolor': '4527A0',
        'bordercolor': '4527A0',
        'color': 'FFF',
        'name': 'The Goblin',
        'expansion': 'dragon_king',
        'selectable': False,
    },
    'the_reaper': {
        'bgcolor': '4527A0',
        'bordercolor': '4527A0',
        'color': 'FFF',
        'name': 'The Reaper',
        'expansion': 'dragon_king',
        'selectable': False,
    },
    'the_rust': {
        'bgcolor': '4527A0',
        'bordercolor': '4527A0',
        'color': 'FFF',
        'name': 'The Rust',
        'expansion': 'dragon_king',
        'selectable': False,
    },
    'the_storm': {
        'bgcolor': '4527A0',
        'bordercolor': '4527A0',
        'color': 'FFF',
        'name': 'The Storm',
        'expansion': 'dragon_king',
        'selectable': False,
    },
    'the_witch': {
        'bgcolor': '4527A0',
        'bordercolor': '4527A0',
        'color': 'FFF',
        'name': 'The Witch',
        'expansion': 'dragon_king',
        'selectable': False,
    },
    'the_sculptor': {
        'bgcolor': '4527A0',
        'bordercolor': '4527A0',
        'color': 'FFF',
        'name': 'The Sculptor',
        'expansion': 'dragon_king',
        'selectable': False,
    },
    'tyrant': {'expansion': 'dragon_king', 'name': 'Tyrant'},

    # Echoes of DEath
    'ethereal': {'expansion': 'echoes_of_death', 'name': "Ethereal"},
    'giants_blood': {'expansion': 'echoes_of_death', 'name': "Giant's Blood"},

    # Dung Beetle Knight
    'beetle_brain': {'expansion': 'dung_beetle_knight', 'name': 'Beetle-brain'},
    'beetle_kin': {'expansion': 'dung_beetle_knight', 'name': 'Beetle-kin'},
    'bug_man': {'expansion': 'dung_beetle_knight', 'name': 'Bug Man'},
    'entomophile': {'expansion': 'dung_beetle_knight', 'name': 'Entomophile'},
    'farmer': {'expansion': 'dung_beetle_knight', 'name': 'Farmer'},
    'met_the_bug_man': {'expansion': 'dung_beetle_knight', 'name': 'Met the Bug Man'},
    'round_stone_trainer': {'expansion': 'dung_beetle_knight','name': 'Round Stone Trainer'},
    'spelunker_of_death': {'expansion': 'dung_beetle_knight','name': 'Spelunker of Death'},

    # Slenderman
    'blotted_out': {
        'bgcolor': '570A75',
        'bordercolor': '470A65',
        'color': 'fff',
        'expansion': 'slenderman',
        'name': 'Blotted Out'
    },
    'forgettable': {'expansion': 'slenderman', 'name': 'Forgettable'},
    'forgotten': {'expansion': 'slenderman', 'name': 'Forgotten'},
    'gloomy': {
        'name': 'Gloomy',
        'bgcolor': '570A75',
        'color': 'fff',
        'expansion': 'slenderman',
    },
    'pod_prisoner': {'expansion': 'slenderman', 'name': 'Pod Prisoner'},
    'stranger': {
        'name': 'Stranger',
        'bgcolor': '570A75',
        'color': 'fff',
        'expansion': 'slenderman',
    },

    # Gorm
    'ancient_gorm_bait': {'expansion': 'gorm', 'name': "Ancient Gorm's Bait"},
    'braved_the_storm': {'expansion': 'gorm', 'name': 'Braved the Storm'},
    'digested': {'expansion': 'gorm', 'name': 'Digested'},
    'gorm_bait': {'expansion': 'gorm', 'name': 'Gorm Bait'},
    'gormchymist': {'expansion': 'gorm', 'name': 'Gormchymist'},
    'living_sacrifice': {'expansion': 'gorm', 'name': 'Living Sacrifice'},

    # Lion Knight
    'brawler': {'expansion': 'lion_knight', 'name': 'Brawler'},
    'dancer': {'expansion': 'lion_knight', 'name': 'Dancer'},
    'hideous': {'expansion': 'lion_knight', 'name': 'Hideous'},
    'monster_worshipper': {'expansion': 'lion_knight', 'name': 'Monster Worshipper'},
    'warlord': {'expansion': 'lion_knight', 'name': 'Warlord'},


    # Sunstalker
    'child_of_the_sun': {
        'name': 'Child of the Sun',
        'bgcolor': 'FFEB3B',
        'bordercolor': 'FFEB3B',
        'expansion': 'sunstalker',
    },
    'eye_patch_badass': {'expansion': 'sunstalker', 'name': 'Eye Patch Badass'},
    'hellion': {'expansion': 'sunstalker', 'name': 'Hellion'},
    'purified': {'expansion': 'sunstalker', 'name': 'Purified'},
    'triplet': {'expansion': 'sunstalker', 'name': 'Triplet'},
    'sun_eater': {
        'name': 'Sun Eater',
        'bgcolor': 'FFEB3B',
        'bordercolor': 'FFEB3B',
        'expansion': 'sunstalker',
    },

    # Manhunter
    'crimson_confectioner': {
        'name': 'Crimson Confectioner',
        'bgcolor': 'c00',
        'bordercolor': 'd00',
        'color': 'fff',
        'expansion': 'manhunter',
    },
    'deranged': {
        'name': 'Deranged',
        'bordercolor': '000',
        'bgcolor': '111',
        'color': 'f00',
        'expansion': 'manhunter',
    },
    'deranged_expression': {
        'name': 'Deranged Expression',
        'bordercolor': '000',
        'bgcolor': '111',
        'color': 'f00',
        'expansion': 'manhunter',
    },
    'manhunter': {
        'name': 'Manhunter',
        'bordercolor': '000',
        'bgcolor': '111',
        'color': 'f00',
        'expansion': 'manhunter',
    },
    'masochist': {
        'name': 'Masochist',
        'bordercolor': '000',
        'bgcolor': '111',
        'color': 'f00',
        'expansion': 'manhunter',
    },
    'recruit': {'expansion': 'manhunter', 'name': 'Recruit'},
    'rested': {
        'name': 'Rested',
        'bgcolor': '4CB848',
        'bordercolor': '4CC868',
        'color': 'FFF',
        'expansion': 'manhunter',
    },
    'sadist': {
        'name': 'Sadist',
        'bordercolor': '000',
        'bgcolor': '111',
        'color': 'f00',
        'expansion': 'manhunter',
    },
    'settlement_watch': {'expansion': 'manhunter', 'name': 'Settlement Watch'},
    'slave': {
        'bordercolor': '000',
        'bgcolor': '111',
        'color': 'f00',
        'expansion': 'manhunter',
        'name': 'Slave'
    },
    'sweet_tooth': {'expansion': 'manhunter', 'name': 'Sweet Tooth'},
    'tuned': {
        'name': 'Tuned',
        'bgcolor': '1C99CD',
        'color': 'FFF',
        'expansion': 'manhunter',
    },
    'warborn': {
        'bgcolor': '000',
        'color': 'f00',
        'expansion': 'manhunter',
        'name': 'Warborn'
    },

    # Spidicules
    'avenger': {'expansion': 'spidicules', 'name': 'Avenger'},
    'black_widow': {'expansion': 'spidicules', 'name': 'Black Widow', 'sex': 'F'},
    'cut_free': {'expansion': 'spidicules', 'name': 'Cut Free'},
    'embalmed': {'expansion': 'spidicules', 'name': 'Embalmed'},
    'harvestman': {'expansion': 'spidicules', 'name': 'Harvestman'},
    'mummified': {'expansion': 'spidicules', 'name': 'Mummified'},
    'mummified_husk': {'expansion': 'spidicules', 'name': 'Mummified Husk'},
    'patient': {'expansion': 'spidicules', 'name': 'Patient'},
    'silk_nest_rescue': {'expansion': 'spidicules', 'name': 'Silk Nest Rescue'},
    'silk_surgeon': {'expansion': 'spidicules', 'name': 'Silk Surgeon'},
    'spider_mastermind': {'expansion': 'spidicules', 'name': 'Spider Mastermind'},
    'spider_puppet': {'expansion': 'spidicules', 'name': 'Spider Puppet'},
    'spider_surgeon': {'expansion': 'spidicules', 'name': 'Spider Surgeon'},
    'stalk_puppet': {'expansion': 'spidicules', 'name': 'Stalk Puppet'},
    'taken': {'expansion': 'spidicules', 'name': 'Taken'},
    'rivals_scar': {'expansion': 'spidicules', 'name': "Rival's Scar"},

    # Flower Knight
    'flower_addict': {'expansion': 'flower_knight', 'name': 'Flower Addict'},
    'guest': {
        'name': 'Guest',
        'bgcolor': '116E17',
        'bordercolor': '116E17',
        'color': '0f0',
        'expansion': 'flower_knight',
    },
    'host': {
        'name': 'Host',
        'bgcolor': '116E17',
        'bordercolor': '116E17',
        'color': '0f0',
        'expansion': 'flower_knight',
    },
    'the_first_guest': {
        'bgcolor': '116E17',
        'bordercolor': '116E17',
        'color': '0f0',
        'expansion': 'flower_knight',
        'name': 'The First Guest'
    },
    'the_first_host': {
        'bgcolor': '116E17',
        'bordercolor': '116E17',
        'color': '0f0',
        'expansion': 'flower_knight',
        'name': 'The First Host'
    },
    'vespertine': {'expansion': 'flower_knight', 'name': 'Vespertine'},

    # White Box
    'gender_swap': {
        'name': 'Gender Swap',
        'bordercolor': 'BC2361',
        'bgcolor': 'FF4081',
        'color': 'fff',
        'expansion': 'white_box',
        'selectable': False,
    },
    'black_guard': {'expansion': 'percival', 'name': "Black Guard"},

    # Lion God
    'necromancer': {'expansion': 'lion_god', 'name': 'Necromancer'},
    'silver_city_explorer': {'expansion': 'lion_god', 'name': 'Silver City Explorer'},
    'worm_bait': {'expansion': 'lion_god', 'name': 'Worm Bait'},
}

mastery = {
    'scythe_master':            {'name': 'Scythe Master', 'selectable': False},
    'katana_master':            {'name': 'Katana Master', 'selectable': False},
    'bow_master':               {'name': 'Bow Master', 'selectable': False},
    'katar_master':             {'name': 'Katar Master', 'selectable': False},
    'sword_master':             {'name': 'Sword Master', 'selectable': False},
    'dagger_master':            {'name': 'Dagger Master', 'selectable': False},
    'shield_master':            {'name': 'Shield Master', 'selectable': False},
    'whip_master':              {'name': 'Whip Master', 'selectable': False},
    'grand_weapon_master':      {'name': 'Grand Weapon Master', 'selectable': False},
    'fist_and_tooth_master':    {'name': 'Fist & Tooth Master', 'selectable': False},
    'club_master':              {'name': 'Club Master', 'selectable': False},
    'spear_master':             {'name': 'Spear Master', 'selectable': False},
    'axe_master':               {'name': 'Axe Master', 'selectable': False},
    'twilight_sword_master':    {'name': 'Twilight Sword master', 'selectable': False},
}

core = {
    'ate_the_fruit':                        {'name': 'Ate the Fruit'},
    'augurer':                              {'name': 'Augurer'},
    'berserker':                            {'name': 'Berserker'},
    'bewitched':                            {'name': 'Bewitched'},
    'blue_savior': {
        'name': 'Blue Savior',
        'bgcolor': '1C99CD',
        'bordercolor': '1C99CD',
        'color': 'FFF',
        'selectable': False,
    },
    'bone_witch': {
        'name': 'Bone Witch',
        'bgcolor': '212121',
        'bordercolor': '313131',
        'color': 'FFF',
    },
    'branded_by_the_lantern':               {'name': 'Branded by the Lantern'},
    'breeder':                              {'name': 'Breeder'},
    'broke_the_silence':                    {'name': 'Broke the Silence'},
    'butcher':                              {'name': 'Butcher'},
    'caratosis': {
        'name': 'Caratosis',
        'bgcolor': 'CD2027',
        'bordercolor': 'CD2027',
        'color': 'FFF',
        'selectable': False,
    },
    'cleared_the_mist':                     {'name': 'Cleared the Mist'},
    'coward':                               {'name': 'Coward'},
    'cursed':                               {'name': 'Cursed'},
    'death_taster':                         {'name': 'Death Taster'},
    'destroyed_genitals':                   {'name': 'Destroyed Genitals'},
    'dimmed_by_the_lantern':                {'name': 'Dimmed by the Lantern'},
    'dormenatus': {
        'name': 'Dormenatus',
        'bgcolor': '4CB848',
        'bordercolor': '4CB848',
        'color': 'FFF',
        'selectable': False,
    },
    'dreamer':                              {'name': 'Dreamer'},
    'endless_arguer':                       {'name': 'Endless Arguer'},
    'experimented_with_lanterns':           {'name': 'Experimented with Lanterns'},
    'fast_runner':                          {'name': 'Fast Runner'},
    'father_of_words':                      {'name': 'Father of Words', 'sex': 'M'},
    'mother_of_words':                      {'name': 'Mother of Words', 'sex': 'F'},
    'first_blood':                          {'name': 'First Blood'},
    'first_daughter':                       {'name': 'First Daughter', 'sex': 'F'},
    'first_father':                         {'name': 'First Father', 'sex': 'M'},
    'first_mother':                         {'name': 'First Mother', 'sex': 'F'},
    'first_son':                            {'name': 'First Son', 'sex': 'M'},
    'foolish':                              {'name': 'Foolish'},
    'forbidden_dancer':                     {'name': 'Forbidden Dancer'},
    'forsaker':                             {'name': 'Forsaker'},
    'founder': {
        'name': 'Founder',
        'bgcolor': 'FFC107',
        'bordercolor': 'FFC107',
    },
    'green_savior': {
        'name': 'Green Savior',
        'bgcolor': '4CB848',
        'bordercolor': '4CB848',
        'color': 'FFF',
        'selectable': False,
    },
    'haunted':                              {'name': 'Haunted'},
    'hero':                                 {'name': 'Hero'},
    'hunter':                               {'name': 'Hunter', 'sex': 'M'},
    'hunter':                               {'name': 'Huntress', 'sex': 'F'},
    'infected':                             {'name': 'Infected'},
    'iron_fist':                            {'name': 'Iron Fist'},
    'kings_curse': {
        'name': "King's Curse",
        'selectable': False,
        'bordercolor': '4D5A2E',
        'bgcolor': 'BEC9B9',
        'color': '5B230F',
    },
    'lantern_experimenter':                 {'name': 'Lantern Experimenter'},
    'leader_of_the_settlement':             {'name': 'Leader of the Settlement'},
    'legendcaller':                         {'name': "Legendcaller"},
    'leper':                                {'name': 'Leper', 'selectable': False},
    "leyline_walker":                       {'name': 'Leyline Walker'},
    'lithophile':                           {'name': 'Lithophile'},
    'lucernae': {
        'name': 'Lucernae',
        'bgcolor': '1C99CD',
        'bordercolor': '1C99CD',
        'color': 'FFF',
        'selectable': False,
    },
    'masticated':                           {'name': 'Masticated'},
    'maw_runner':                           {'name': 'Maw Runner'},
    'metal_jaw':                            {'name': 'Metal Jaw'},
    'monster':                              {'name': 'Monster'},
    'monster_teeth':                        {'name': 'Monster Teeth'},
    'murderer':                             {'name': 'Murderer'},
    'one_eyed':                             {'name': 'One-eyed'},
    'plague_bearer':                        {'name': 'Plague-bearer'},
    'pure_warrior':                         {'name': 'Pure Warrior'},
    'rival':                                {'name': 'Rival'},
    'red_savior': {
        'name': 'Red Savior',
        'bgcolor': 'CD2027',
        'bordercolor': 'CD2027',
        'color': 'FFF',
        'selectable': False,
    },
    'sacrificed':                           {'name': 'Sacrificed'},
    'scarred':                              {'name': 'Scarred'},
    'scarred_by_the_first_grave':           {'name': 'Scarred by the First Grave'},
    'scrap_scavenger':                      {'name': 'Scrap Scavenger'},
    'shining':                              {'name': 'Shining'},
    'silence_breaker':                      {'name': 'Silence Breaker'},
    'skull_eater':                          {'name': 'Skull Eater'},
    'slayer':                               {'name': 'Slayer'},
    'sniper':                               {'name': 'Sniper'},
    'speaker_of_the_first_words':           {'name': 'Speaker of the First Words'},
    'straggler':                            {'name': 'Straggler'},
    'swamp_explorer':                       {'name': 'Swamp Explorer'},
    'swift_footed':                         {'name': 'Swift-footed'},
    'the_blind':                            {'name': 'The Blind'},
    'the_brave':                            {'name': 'The Brave'},
    'the_chef':                             {'name': 'The Chef'},
    'the_dead':                             {'name': 'The Dead'},
    'the_doomed':                           {'name': 'The Doomed'},
    'the_fertile':                          {'name': 'The Fertile'},
    'the_insane':                           {'name': 'The Insane'},
    'the_mad':                              {'name': 'The Mad'},
    'the_silent':                           {'name': 'The Silent'},
    'thundercaller':                        {'name': 'Thundercaller'},
    'triathlete':                           {'name': 'Triathlete'},
    'twilight_knight': {
        'name': 'Twilight Knight',
        'bgcolor': '546E7A',
        'bordercolor': '546E7A',
        'color': 'fff',
        'selectable': False,
    },
    'twilight_lineage': {
        'name': 'Twilight Lineage',
        'bgcolor': '546E7A',
        'bordercolor': '546E7A',
        'color': 'fff',
    },
    'twilight_sword': {
        'name': 'Twilight Sword',
        'bgcolor': '546E7A',
        'bordercolor': '546E7A',
        'color': 'fff',
        'selectable': False,
    },
    'twin':                                 {'name': 'Twin'},
    'undisputed_boss_of_the_settlement':    {'name': 'Undisputed boss of the settlement'},
    'urine_soaked':                         {'name': 'Urine-soaked'},
    'voice_of_reason':                      {'name': 'Voice of Reason'},
    'vomit_soaked':                         {'name': 'Vomit-soaked'},
    'wanderer':                             {'name': 'Wanderer'},
    'white_haired':                         {'name': 'White-haired'},
    'white_speaker':                        {'name': 'White Speaker', 'sex': 'F',},
    'witness':                              {'name': 'Witness'},
}
