core = {

    # catarium
    'cat_eye_circlet': {
        'type': 'catarium',
        'name': 'Cat Eye Circlet',
        'keywords': ['item','jewelry','other'],
        'desc': '<font class="kdm_font">a</font>: Reveal the next 3 monster hit locations and put them back in any order.',
    },
    'cat_fang_knife': {
        'type': 'catarium',
        'name': 'Cat Fang Knife',
        'keywords': ['weapon','melee','dagger','bone'],
        'speed': 3,
        'accuracy': 6,
        'strength': 2,
    },
    'cat_gut_bow': {
        'type': 'catarium',
        'name': 'Cat Gut Bow',
        'keywords': ['weapon','ranged','bow','two-handed'],
        'rules': ['Cumbersom','Range: 6'],
        'desc': '<b>Aim:</b> When you attack, before rolling to hit, you may reduce the speed of this weapon by 1 to gain +2 accuracy for that attack.',
        'speed': 2,
        'accuracy': 7,
        'strength': 3,
    },
    'claw_head_arrow': {
        'attack': (1,6,6),
        'speed': 1,
        'accuracy': 6,
        'strength': 6,
        'type': 'catarium',
        'name': 'Claw Head Arrow',
        'keywords': ['item','ammuntion','arrow'],
        'rules': ['Slow','Ammo - Bow'],
        'desc': 'If you hit, monster gains -1 evasion token. Use once per showdown.',
    },
    'frenzy_drink': {
        'type': 'catarium',
        'name': 'Frenzy Drink',
        'keywords': ['item','consumable','fragile'],
        'desc': '<font class="kdm_font">a</font> <b>Consume:</b> Suffer <b>Frenzy</b> brain trauma. Can be used once per showdown.',
    },
    'king_spear': {
        'type': 'catarium',
        'name': 'King Spear',
        'keywords': ['weapon','melee','spear','heavy','two-handed'],
        'rules': ['Reach 2'],
    },
    'lion_beast_katar': {
        'type': 'catarium',
        'name': 'Lion Beast Katar',
        'keywords': ['weapon','melee','katar'],
        'rules': ['Deadly','Paired'],
    },
    'lion_headdress': {
        'type': 'catarium',
        'name': 'Lion Headdress',
        'keywords': ['item','flammable'],
        'rules': ['Accessory'],
    },
    'lion_skin_cloak': {
        'type': 'catarium',
        'name': 'Lion Skin Cloak',
        'keywords': ['armor','fur','bone','heavy','flammable'],
        'desc': 'Reduce damage from every hit suffered by 1, to a minimum of 1.',
    },
    'whisker_harp': {
        'type': 'catarium',
        'name': 'Whisker Harp',
        'keywords': ['item','instrument','noisy'],
        'desc': 'On <b>Arrival</b>, all survivors gain +1 survival.<br/><font class="kdm_font">a</font>: Strum, roll 1d10. On a result of 6+ discard 1 <b>mood</b> currently in play.',
    },
    'white_lion_armor_set': {'type': 'catarium', 'name': 'White Lion Armor Set'},
    'white_lion_boots': {
        'type': 'catarium',
        'name': 'White Lion Boots',
        'keywords': ['armor','set','fur','heavy'],
    },
    'white_lion_coat': {
        'type': 'catarium',
        'name': 'White Lion Coat',
        'desc': '<b>Pounce:</b> Spend <font class="kdm_font">c</font> and <font class="kdm_font">a</font> to move 3 spaces in a straight line. Then, if you moved 3 spaces, activate a melee weapon with +1 strength.',
    },
    'white_lion_gauntlets': {
        'type': 'catarium',
        'name': 'White Lion Gauntlet',
        'keywords': ['armor','set','fur','heavy'],
        'desc': 'When you <b>Pounce</b>, gain +1 accuracy for your next attack this turn.',
    },
    'white_lion_helm': {
        'type': 'catarium',
        'name': 'White Lion Helm',
        'keywords': ['armor','set','fur','heavy'],
    },
    'white_lion_skirt': {
        'type': 'catarium',
        'name': 'White Lion Skirt',
        'keywords': ['armor','set','fur','heavy'],
    },


    'adventure_sword': {
        'type': 'rare_gear',
        'name': 'Adventure Sword',
        'keywords': ['weapon','melee','sword','finesse','other'],
        'rules': ['Unique','Irreplaceable'],
        'desc': "Your courage is added to this weapon's strength.",
    },
    'almanac': {'type': 'barber_surgeon', 'name': 'Almanac'},
    'arc_bow': {'type': 'plumery', 'name': 'Arc Bow'},
    'bandages': {
        'type': 'skinnery',
        'name': 'Bandages',
        'keywords': ['item'],
        'desc': '<font class="kdm_font">a</font>: Remove up to 2 bleeding tokens from yourself or an adjacent survivor.',
    },
    'beacon_shield': {'type': 'blacksmith', 'name': 'Beacon Shield'},
    'beast_knuckle': {'type': 'stone_circle', 'name': 'Beast Knuckle'},
    'bird_bread': {'type': 'plumery', 'name': 'Bird Bread'},
    'blood_paint': {'type': 'stone_circle', 'name': 'Blood Paint'},
    'bloom_sphere': {'type': 'plumery', 'name': 'Bloom Sphere'},
    'blue_charm': {'type': 'stone_circle', 'name': 'Blue Charm'},

    # bone smith
    'bone_axe': {
        'type': 'bone_smith',
        'name': 'Bone Axe',
        'rules': 'Savage',
        'keywords': ['weapon','melee','axe','bone'],
    },
    'bone_blade': {
        'type': 'bone_smith',
        'name': 'Bone Blade',
        'rules': ['Frail'],
        'keywords': ['weapon','melee','sword','bone'],
    },
    'bone_club': {
        'type': 'bone_smith',
        'name': 'Bone Club',
        'resource_cost': {'bone': 3},
        'keywords': ['weapon','melee','two-handed','heavy','club','bone'],
        'rules': ['Cumbersome'],
    },
    'bone_dagger': {
        'type': 'bone_smith',
        'name': 'Bone Dagger',
        'keywords': ['weapon','melee','dagger','bone'],
        'desc': 'On a <b>Perfect hit</b>, gain +1 survival.',
    },
    'bone_darts': {
        'type': 'bone_smith',
        'name': 'Bone Darts',
        'rules': ['Range: 6', 'Frail'],
        'keywords': ['weapon','ranged','thrown','bone'],
    },
    'bone_earrings': {'type': 'stone_circle', 'name': 'Bone Earrings'},
    'bone_pickaxe': {
        'type': 'bone_smith',
        'name': 'Bone Pickaxe',
        'keywords': ['item','tool','pickaxe','bone'],
        'desc': 'After Hunt phase setup, place the <b>Mineral Gathering</b> event on any hunt space.',
    },
    'bone_sickle': {
        'type': 'bone_smith',
        'name': 'Bone Sickle',
        'keywords': ['item','tool','sickle','bone'],
        'desc': 'After Hunt phase setup, place the <b>Herb Gathering</b> event on any hunt space.',
    },
    'boss_mehndi': {'type': 'stone_circle', 'name': 'Boss Mehndi'},
    'brain_mint': {'type': 'barber_surgeon', 'name': 'Brain Mint'},
    'bug_trap': {
        'type': 'barber_surgeon',
        'name': 'Bug Trap',
    },
    'butcher_cleaver': {
        'type': 'rare_gear',
        'name': 'Butcher Cleaver',
        'keywords': ['weapon','melee','axe','other'],
        'rules': ['Paired', 'Sentient', 'Irreplaceable'],
    },
    'cloth': {
        'type': 'starting_gear',
        'name': 'Cloth',
        'keywords': ['armor'],
        'desc': 'The Cloth protects your waist. Gain 1 armor point at the waist hit location.',
    },
    'counterweighted_axe': {
        'type': 'weapon_crafter',
        'name': 'Counterweighted Axe',
        'keywords': ['weapon','melee','axe','two-handed'],
        'rules': ['Reach 2']
    },
    'crest_crown': {'type': 'plumery', 'name': 'Crest Crown'},
    'dragon_slayer': {'type': 'blacksmith', 'name': 'Dragon Slayer'},
    'dried_acanthus': {
        'type': 'organ_grinder',
        'name': 'Dried Acanthus',
        'keywords': ['item','herb','consumable'],
        'desc': ['When you <b>depart</b>, gain +2 survival. When you suffer a severe injury, ignore it and archive this card instead.'],
    },
    'elder_earrings': {'type': 'barber_surgeon', 'name': 'Elder Earrings'},
    'feather_mantle': {'type': 'plumery', 'name': 'Feather Mantle'},
    'feather_shield': {'type': 'plumery', 'name': 'Feather Shield'},
    'fecal_salve': {
        'type': 'organ_grinder',
        'name': 'Fecal Salve',
        'keywords': ['item','balm','stinky'],
        'desc': 'When you <b>depart</b>, gain +1 survival<br/><font class="kdm_font">a</font>: You are not a a <b>threat</b> until you attack. If you have the <b>priority target</b> token, remove it.',
    },
    'final_lantern': {
        'type': 'exhausted_lantern_hoard',
        'name': 'Final Lantern',
        'keywords': ['item','other'],
        'rules': ['Vital'],
    },
    'finger_of_god': {
        'type': 'weapon_crafter',
        'name': 'Finger of God',
        'keywords': ['weapon','melee','spear','two-handed'],
        'rules': ['Reach 2'],
    },
    'first_aid_kit': {'type': 'barber_surgeon', 'name': 'First Aid Kit'},
    'forsaker_mask': {
        'type': 'rare_gear',
        'name': 'Forsaker Mask',
        'keywords': ['item','mask','metal','other'],
        'rules': ['Unique','Irreplaceable','Accessory'],
        'desc': 'During the Aftermath, you run off into the darkness never to be seen again.<hr/>During the Settlement Phase, you may archive this item to build the <b>Mask Maker</b> location.',
    },
    'founding_stone': {
        'type': 'starting_gear',
        'name': 'Founding Stone',
        'keywords': ['weapon','melee','stone'],
        'desc': 'Spend <font class="kdm_font">a</font> to sling the stone from anywhere on the board! Archive this card for 1 automatic hit that inflicts a critical wound.',
    },
    'green_charm': {'type': 'stone_circle', 'name': 'Green Charm'},
    'hollow_sword': {'type': 'plumery', 'name': 'Hollow Sword'},
    'hollowpoint_arrow': {'type': 'plumery', 'name': 'Hollowpoint Arrow'},
    'hours_ring': {'type': 'plumery', 'name': 'Hours Ring'},
    'hunter_whip': {'type': 'leather_worker', 'name': 'Hunter Whip'},
    'lance_of_longinus': {'type': 'stone_circle',
                       'name': 'Lance Of Longinus'},
    'lantern_armor_set': {'type': 'blacksmith', 'name': 'Lantern Armor Set'},
    'lantern_cuirass': {'type': 'blacksmith', 'name': 'Lantern Cuirass'},
    'lantern_dagger': {'type': 'blacksmith', 'name': 'Lantern Dagger'},
    'lantern_gauntlets': {'type': 'blacksmith', 'name': 'Lantern Gauntlets'},
    'lantern_glaive': {'type': 'blacksmith', 'name': 'Lantern Glaive'},
    'lantern_greaves': {'type': 'blacksmith', 'name': 'Lantern Greaves'},
    'lantern_halberd': {
        'type': 'rare_gear',
        'name': 'Lantern Halberd',
        'keywords': ['weapon','melee','two-handed','spear','other'],
        'rules': ['Reach 2','Irreplaceable','Unique'],
        'desc': 'After attacking, if standing, you may move up to 2 spaces directly away from the monster.',
    },
    'lantern_helm': {'type': 'blacksmith', 'name': 'Lantern Helm'},
    'lantern_mail': {'type': 'blacksmith', 'name': 'Lantern Mail'},
    'lantern_sword': {'type': 'blacksmith', 'name': 'Lantern Sword'},
    'leather_armor_set': {'type': 'leather_worker',
                       'name': 'Leather Armor Set'},
    'leather_boots': {'type': 'leather_worker', 'name': 'Leather Boots'},
    'leather_bracers': {'type': 'leather_worker', 'name': 'Leather Bracers'},
    'leather_cuirass': {'type': 'leather_worker', 'name': 'Leather Cuirass'},
    'leather_mask': {'type': 'leather_worker', 'name': 'Leather Mask'},
    'leather_skirt': {'type': 'leather_worker', 'name': 'Leather Skirt'},
    'lucky_charm': {
        'type': 'organ_grinder',
        'name': 'Lucky Charm',
        'keywords': ['item','jewelry'],
    },
    'monster_grease': {
        'type': 'organ_grinder',
        'name': 'Monster Grease',
        'keywords': ['item','consumable','soluble','stinky'],
        'desc': 'Gain +1 evasion.',
    },
    'monster_tooth_necklace': {
        'type': 'organ_grinder',
        'name': 'Monster Tooth Necklace',
        'keywords': ['item','jewelry','bone'],
        'desc': 'Gain +2 strength.',
    },
    'muramasa': {
        'type': 'rare_gear',
        'name': 'Muramasa',
        'keywords': ['weapon','melee','katana', 'two-handed','other'],
        'rules': ['Frail','Sharp','Sentient','Deadly 2','Unique'],
        'desc': 'When you critically wound with this weapon, gain 2 bleeding tokens.',
    },
    'musk_bomb': {'type': 'barber_surgeon', 'name': 'Musk Bomb'},
    'oxidized_beacon_shield': {'type': 'exhausted_lantern_hoard',
                            'name': 'Oxidized Beacon Shield'},
    'oxidized_lantern_dagger': {'type': 'exhausted_lantern_hoard',
                             'name': 'Oxidized Lantern Dagger'},
    'oxidized_lantern_glaive': {'type': 'exhausted_lantern_hoard',
                             'name': 'Oxidized Lantern Glaive'},
    'oxidized_lantern_helm': {'type': 'exhausted_lantern_hoard',
                           'name': 'Oxidized Lantern Helm'},
    'oxidized_lantern_sword': {'type': 'exhausted_lantern_hoard',
                            'name': 'Oxidized Lantern Sword'},
    'oxidized_ring_whip': {'type': 'exhausted_lantern_hoard', 'name': 'Oxidized Ring Whip'},
    'perfect_slayer': {'type': 'blacksmith', 'name': 'Perfect Slayer'},
    'phoenix_armor_set': {'type': 'plumery', 'name': 'Phoenix Armor Set'},
    'phoenix_faulds': {'type': 'plumery', 'name': 'Phoenix Faulds'},
    'phoenix_gauntlet': {'type': 'plumery', 'name': 'Phoenix Gauntlet'},
    'phoenix_greaves': {'type': 'plumery', 'name': 'Phoenix Greaves'},
    'phoenix_helm': {'type': 'plumery', 'name': 'Phoenix Helm'},
    'phoenix_plackart': {'type': 'plumery', 'name': 'Phoenix Plackart'},
    'portcullis_key': {'type': 'other', 'name': 'Portcullis Key'},
    'rainbow_katana': {
        'type': 'weapon_crafter',
        'name': 'Rainbow Katana',
        'keywords': ['weapon','melee','katana','finesse','two-handed'],
        'rules': ['Frail',],
    },
    'rawhide_armor_set': {'type': 'skinnery', 'name': 'Rawhide Armor Set'},
    'rawhide_boots': {
        'type': 'skinnery',
        'name': 'Rawhide Boots',
        'keywords': ['armor','set','rawhide'],
        'desc': 'When you <b>depart</b>, gain +1 survival',
    },
    'rawhide_drum': {
        'type': 'skinnery',
        'name': 'Rawhide Drum',
        'keywords': ['item','rawhide','instrument','noisy'],
        'desc': 'On <b>Arrival</b>, all survivors gain +1 insanity.<br/>Inspirational drumming! When you perform <b>encourage</b>, all non-deaf survivors are affected.',
    },
    'rawhide_gloves': {
        'type': 'skinnery',
        'name': 'Rawhide Gloves',
        'desc': 'When you <b>depart</b>, gain +1 survival',
        'keywords': ['armor','set','rawhide'],
    },
    'rawhide_headband': {
        'type': 'skinnery',
        'name': 'Rawhide Headband',
        'keywords': ['armor','set','rawhide',],
    },
    'rawhide_pants': {
        'type': 'skinnery',
        'name': 'Rawhide Pants',
        'keywords': ['armor','set','rawhide',],
    },
    'rawhide_vest': {
        'type': 'skinnery',
        'name': 'Rawhide Vest',
        'keywords': ['armor','set','rawhide',],
    },
    'rawhide_whip': {
        'type': 'skinnery',
        'name': 'Rawhide Whip',
        'keywords': ['weapon','melee','whip','rawhide'],
        'desc': '<b>Provoke:</b> When you wound with this weapon, gain the <b>priority target</b> token.',
    },
    'red_charm': {'type': 'stone_circle', 'name': 'Red Charm'},
    'regal_faulds': {
        'type': 'rare_gear',
        'name': 'Regal Faulds',
        'keywords': ['armor','bone','metal'],
        'rules': ['Cursed'],
        'desc': "At the Aftermath, <font class='kdm_font'>g</font> <b>King's Curse</b>.",
    },
    'regal_gauntlet': {
        'type': 'rare_gear',
        'name': 'Regal Gauntlet',
        'keywords': ['armor','bone','metal'],
        'rules': ['Cursed'],
        'desc': "At the Aftermath, <font class='kdm_font'>g</font> <b>King's Curse</b>.",
    },
    'regal_greaves': {
        'type': 'rare_gear',
        'name': 'Regal Greaves',
        'keywords': ['armor','bone','metal'],
        'rules': ['Cursed'],
        'desc': "At the Aftermath, <font class='kdm_font'>g</font> <b>King's Curse</b>.",
    },
    'regal_helm': {
        'type': 'rare_gear',
        'name': 'Regal Helm',
        'keywords': ['armor','bone','metal'],
        'rules': ['Cursed'],
        'desc': "At the Aftermath, <font class='kdm_font'>g</font> <b>King's Curse</b>.",
    },
    'regal_plackart': {
        'type': 'rare_gear',
        'name': 'Regal Plackart',
        'keywords': ['armor','bone','metal'],
        'rules': ['Cursed'],
        'desc': "At the Aftermath, <font class='kdm_font'>g</font> <b>King's Curse</b>.",
    },
    'ring_whip': {'type': 'blacksmith', 'name': 'Ring Whip'},
    'round_leather_shield': {'type': 'leather_worker',
                          'name': 'Round Leather Shield'},
    'scavenger_kit': {'type': 'barber_surgeon', 'name': 'Scavenger Kit'},
    'scrap_dagger': {
        'type': 'weapon_crafter',
        'name': 'Scrap Dagger',
        'keywords': ['weapon','melee','dagger','metal'],
        'desc': "On a <b>Perfect hit</b>, the edge sharpens. Gain +2 strength for the rest of the attack.",
    },
    'scrap_shield': {'type': 'blacksmith', 'name': 'Scrap Shield'},
    'scrap_sword': {
        'type': 'weapon_crafter',
        'name': 'Scrap Sword',
        'keywords': ['weapon','melee','sword','metal'],
        'desc': "On a <b>Perfect hit</b>, the edge sharpens. Gain +4 strength for the rest of the attack.",
    },
    'screaming_armor_set': {'type': 'stone_circle','name': 'Screaming Armor Set'},
    'screaming_bracers': {'type': 'stone_circle','name': 'Screaming Bracers'},
    'screaming_coat': {'type': 'stone_circle', 'name': 'Screaming Coat'},
    'screaming_horns': {'type': 'stone_circle', 'name': 'Screaming Horns'},
    'screaming_leg_warmers': {'type': 'stone_circle','name': 'Screaming Leg Warmers'},
    'screaming_skirt': {'type': 'stone_circle', 'name': 'Screaming Skirt'},
    'skull_helm': {
        'type': 'bone_smith',
        'name': 'Skull Helm',
        'keywords': ['armor','bone','fragile'],
        'desc': 'When you suffer a severe head injury, the Skull Helm is destroyed. Archive this card.',
    },
    'skullcap_hammer': {
        'type': 'weapon_crafter',
        'name': 'Skullcap Hammer',
        'desc': 'On a <b>Perfect Hit</b>, the monster is dazed, and gains -1 speed token until the end of its turn. A monster can be dazed once per round.',
        'keywords': ['weapon','melee','club','bone'],
    },
    'sonic_tomahawk': {'type': 'plumery', 'name': 'Sonic Tomahawk'},
    'speed_powder': {'type': 'barber_surgeon', 'name': 'Speed Powder'},
    'steel_shield': {
        'type': 'rare_gear',
        'name': 'Steel Shield',
        'keywords': ['weapon','melee','shield','metal','heavy'],
        'rules': ['Irreplaceable',],
        'desc': '-3 movement.<br/>Spend <font class="kdm_font">a</font> or survival to ignore a hit.',
    },
    'steel_sword': {
        'type': 'rare_gear',
        'name': 'Steel Sword',
        'keywords': ['weapon','melee','sword','finesse','metal'],
        'rules': ['Irreplaceable','Slow','Sharp'],
        'desc': 'On a <b>Perfect hit</b>, the edge sharpens. Gain +1d10 strength for the rest of the attack.',
    },
    'stone_noses': {
        'type': 'organ_grinder',
        'name': 'Stone Noses',
        'keywords': ['item','jewelry'],
        'desc': 'On <b>Arrival</b>, gain +1 survival, +1 insanity.',
    },
    "survivors_lantern": {
        'type': 'exhausted_lantern_hoard',
        'name': "Survivor's Lantern",
        'keywords': ['item','lantern'],
    },
    'thunder_maul': {
        'type': 'rare_gear',
        'name': 'Thunder Maul',
        'keywords': ['weapon','melee','club','two-handed','other'],
        'rules': ['Irreplaceable', 'Unique','Cursed'],
        'desc': 'On a <b>Perfect hit</b>, the monster is knocked down. Suffer a severe arm injury. All non-deaf survivors suffer 1 brain damage.',
    },
    'twilight_sword': {
        'type': 'rare_gear',
        'name': 'Twilight Sword',
        'keywords': ['weapon','melee','two-handed', 'finesse', 'other'],
        'rules': ['Slow','Cursed','Cumbersome','Sentient','Irreplaceable'],
        'desc': 'Gains <b>Devastating 2</b> when fighting the Watcher.<br/>* Accuracy is 9 - Twilight Sword proficiency level.',
    },

    # mask maker
    'antelope_mask': {
        'type': 'mask_maker',
        'name': 'Antelope Mask',
        'keywords': ['item','mask','bone','other'],
        'rules': ['Unique','Irreplaceable','Accessory'],
    },
    'death_mask': {
        'type': 'mask_maker',
        'name': 'Death Mask',
        'keywords': ['item','mask','bone','other'],
        'rules': ['Unique','Irreplaceable','Accessory'],
        'desc': 'If you have no affinities, gain +4 luck and suffer -4 to all severe injury rolls.',
    },
    'god_mask': {
        'type': 'mask_maker',
        'name': 'God Mask',
        'keywords': ['item','mask','bone','other'],
        'rules': ['Unique','Irreplaceable','Accessory'],
    },
    'man_mask': {
        'type': 'mask_maker',
        'name': 'Man Mask',
        'keywords': ['item','mask','bone','other'],
        'rules': ['Unique','Irreplaceable','Accessory'],
    },
    'phoenix_mask': {
        'type': 'mask_maker',
        'name': 'Phoenix Mask',
        'keywords': ['item','mask','bone','other'],
        'rules': ['Unique','Irreplaceable','Accessory'],
    },
    'white_lion_mask': {
        'type': 'mask_maker',
        'name': 'White Lion Mask',
        'keywords': ['item','mask','bone','other'],
        'rules': ['Unique','Irreplaceable','Accessory'],
    },

    # weapon crafter
    'blood_sheath': {
        'type': 'weapon_crafter',
        'name': 'Blood Sheath',
        'keywords': ['item','bone','other'],
        'rules': ['Block 1'],
        'desc': 'When Rainbow Katana is left of Blood Sheath, it loses <b>Frail</b> and gains <b>Sharp</b> (add 1d10 strength to each wound attempt).',
    },
    'whistling_mace': {
        'type': 'weapon_crafter',
        'name': 'Whistling Mace',
        'keywords': ['weapon','melee','club','bone'],
        'desc': 'On a <b>Perfect hit</b>, reveal the next AI card. Place it on top or bottom of the AI deck.',
        'rules': ['Unwieldy'],
    },
    'zanbato': {
        'type': 'weapon_crafter',
        'name': 'Zanbato',
        'keywords': ['weapon','melee','grand weapon','two-handed','bone'],
        'rules': ['Slow','Frail','Deadly'],
    },
}

beta_challenge_scenarios = {
    'arm_of_the_first_tree': {
        'keywords': ['weapon', 'melee', 'club'],
        'expansion': 'beta_challenge_scenarios',
        'type': 'rare_gear',
        'name': 'Arm of the First Tree'
    },
    "ayas_spear": {'keywords': ['weapon', 'melee', 'spear'],
                 'expansion': 'beta_challenge_scenarios',
                 'type': 'rare_gear',
                 'name': "Aya's Spear"},
    "ayas_sword": {'keywords': ['weapon', 'melee', 'sword'],
                 'expansion': 'beta_challenge_scenarios',
                 'type': 'rare_gear',
                 'name': "Aya's Sword"
    },
    'cola_bottle_lantern': {
        'keywords': ['item', 'fragile', 'other'],
        'expansion': 'beta_challenge_scenarios',
        'type': 'rare_gear',
        'name': 'Cola Bottle Lantern',
    },
    'fairy_bottle': {
        'keywords': ['item', 'fragile', 'other'],
        'expansion': 'beta_challenge_scenarios',
        'type': 'rare_gear',
        'name': 'Fairy Bottle'
    },
    'giant_stone_face': {
        'keywords': ['weapon','melee', 'grand', 'heavy', 'two-handed', 'stone'],
        'expansion': 'beta_challenge_scenarios',
        'type': 'rare_gear',
        'name': 'Giant Stone Face'
    },
 'petal_lantern': {'keywords': ['item', 'lantern', 'other'],
                   'expansion': 'beta_challenge_scenarios',
                   'type': 'rare_gear',
                   'name': 'Petal Lantern'},
 'piranha_helm': {'keywords': ['armor', 'set', 'rawhide'],
                  'expansion': 'beta_challenge_scenarios',
                  'type': 'rare_gear',
                  'name': 'Piranha Helm'},
 "scouts_tunic": {'keywords': ['armor', 'set', 'leather'],
                   'expansion': 'beta_challenge_scenarios',
                   'type': 'rare_gear',
                   'name': "Scout's Tunic"},
 'stone_arm': {'keywords': ['item', 'stone', 'heavy'],
               'expansion': 'beta_challenge_scenarios',
               'type': 'rare_gear',
               'name': 'Stone Arm'},

}

gorm = {
    'acid_tooth_dagger': {
        'expansion': 'gorm',
        'type': 'gormery',
        'name': 'Acid Tooth Dagger'
    },
    'armor_spikes': {
        'expansion': 'gorm',
        'type': 'gormery',
        'name': 'Armor Spikes'
    },
    'black_sword': {
        'expansion': 'gorm',
        'type': 'gormery',
        'name': 'Black Sword'
    },
    'gaxe': {
        'expansion': 'gorm',
        'type': 'gormery',
        'name': 'Gaxe'
    },
 'gorment_armor_set': {'expansion': 'gorm',
                       'type': 'gormery',
                       'name': 'Gorment Armor Set'},
 'gorment_boots': {'expansion': 'gorm',
                   'type': 'gormery',
                   'name': 'Gorment Boots'},
 'gorment_mask': {'expansion': 'gorm',
                  'type': 'gormery',
                  'name': 'Gorment Mask'},
 'gorment_sleeves': {'expansion': 'gorm',
                     'type': 'gormery',
                     'name': 'Gorment Sleeves'},
 'gorment_suit': {'expansion': 'gorm',
                  'type': 'gormery',
                  'name': 'Gorment Suit'},
 'gorn': {'expansion': 'gorm', 'type': 'gormery', 'name': 'Gorn'},
 'greater_gaxe': {'expansion': 'gorm',
                  'type': 'gormery',
                  'name': 'Greater Gaxe'},
 'healing_potion': {'type': 'gormchymist', 'name': 'Healing Potion'},
 'knuckle_shield': {'expansion': 'gorm',
                    'type': 'gormery',
                    'name': 'Knuckle Shield'},
 'life_elixir': {'type': 'gormchymist', 'name': 'Life Elixir'},
 'power_potion': {'type': 'gormchymist', 'name': 'Power Potion'},
 'pulse_lantern': {'expansion': 'gorm',
                   'type': 'gormery',
                   'name': 'Pulse Lantern'},
 'regeneration_suit': {'expansion': 'gorm',
                       'type': 'gormery',
                       'name': 'Regeneration Suit'},
 'rib_blade': {'expansion': 'gorm',
               'type': 'gormery',
               'name': 'Rib Blade'},
 'riot_mace': {'expansion': 'gorm',
               'type': 'gormery',
               'name': 'Riot Mace'},
 'steadfast_potion': {'type': 'gormchymist', 'name': 'Steadfast Potion'},
 'wisdom_potion': {'type': 'gormchymist', 'name': 'wisdom potion'},
}

spidicules = {
    # rare gear
    'grinning_visage': {
        'keywords': ['weapon', 'melee', 'shield'],
        'desc': """When you wound with this shield, you may spend 1 survival to add <font class="inline_shield">1</font> to all hit locations.<br/>Limit, once per attack.""",
        'expansion': 'spidicules',
        'type': 'rare_gear',
        'name': 'Grinning Visage',
    },

    # silk mill
    'amber_edge': {
        'expansion': 'spidicules',
        'type': 'silk_mill',
        'name': 'Amber Edge'
    },
    'amber_poleaxe': {
        'expansion': 'spidicules',
        'type': 'silk_mill',
        'name': 'Amber Poleaxe'
    },
    'blue_ring': {
        'expansion': 'spidicules',
        'type': 'silk_mill',
        'name': 'Blue Ring'
    },
    'green_ring': {
        'expansion': 'spidicules',
        'type': 'silk_mill',
        'name': 'Green Ring'
    },
 'hooded_scrap_katar': {'expansion': 'spidicules',
                        'type': 'silk_mill',
                        'name': 'Hooded Scrap Katar'},
 'red_ring': {'expansion': 'spidicules',
              'type': 'silk_mill',
              'name': 'Red Ring'},
 'silk_armor_set': {'expansion': 'spidicules',
                    'type': 'silk_mill',
                    'name': 'Silk Armor Set'},
 'silk_body_suit': {'expansion': 'spidicules',
                    'type': 'silk_mill',
                    'name': 'Silk Body Suit'},
 'silk_bomb': {'expansion': 'spidicules',
               'type': 'silk_mill',
               'name': 'Silk Bomb'},
 'silk_boots': {'expansion': 'spidicules',
                'type': 'silk_mill',
                'name': 'Silk Boots'},
 'silk_robes': {'expansion': 'spidicules',
                'type': 'silk_mill',
                'name': 'Silk Robes'},
 'silk_sash': {'expansion': 'spidicules',
               'type': 'silk_mill',
               'name': 'Silk Sash'},
 'silk_turban': {'expansion': 'spidicules',
                 'type': 'silk_mill',
                 'name': 'Silk Turban'},
 'silk_whip': {'expansion': 'spidicules',
               'type': 'silk_mill',
               'name': 'Silk Whip'},
 'silk_wraps': {'expansion': 'spidicules',
                'type': 'silk_mill',
                'name': 'Silk Wraps'},
 'throwing_knife': {'expansion': 'spidicules',
                    'type': 'silk_mill',
                    'name': 'Throwing Knife'},
    'the_weaver': {
        'desc': 'When you wound a monster, add <font class="inline_shield">1</font> to a random hit location.',
        'expansion': 'spidicules',
        'type': 'rare_gear',
        'name': 'The Weaver',
        'keywords': ['weapon', 'melee', 'sword', 'amber'],
    },
}

lion_god = {
    'ancient_lion_claws': {'expansion': 'lion_god',
                        'type': 'rare_gear',
                        'name': 'Ancient Lion Claws'
    },
    'bone_witch_mehndi': {'expansion': 'lion_god',
                       'type': 'rare_gear',
                       'name': 'Bone Witch Mehndi'
    },
    "butchers_blood": {'expansion': 'lion_god',
                     'type': 'rare_gear',
                     'name': "Butcher's Blood"
    },
    'death_mehndi': {
        'expansion': 'lion_god',
        'type': 'rare_gear',
        'name': 'Death Mehndi'
    },
 'glyph_of_solitude': {'expansion': 'lion_god',
                       'type': 'rare_gear',
                       'name': 'Glyph of Solitude'},
 'golden_plate': {'expansion': 'lion_god',
                  'type': 'rare_gear',
                  'name': 'Golden Plate'},
 'lantern_mehndi': {'expansion': 'lion_god',
                    'type': 'rare_gear',
                    'name': 'Lantern Mehndi'},
 'lion_god_statue': {'expansion': 'lion_god',
                     'type': 'rare_gear',
                     'name': 'Lion God Statue'},
    "necromancers_eye": {
        'expansion': 'lion_god',
        'type': 'rare_gear',
        'name': "Necromancer's Eye",
    },
}

sunstalker = {
 'apostle_crown': {'expansion': 'sunstalker',
                   'type': 'sacred_pool',
                   'name': 'Apostle Crown'},
 'cycloid_scale_armor': {'expansion': 'sunstalker',
                         'type': 'skyreef_sanctuary',
                         'name': 'Cycloid Scale Armor'},
 'cycloid_scale_hood': {'expansion': 'sunstalker',
                        'type': 'skyreef_sanctuary',
                        'name': 'Cycloid Scale Hood'},
 'cycloid_scale_jacket': {'expansion': 'sunstalker',
                          'type': 'skyreef_sanctuary',
                          'name': 'Cycloid Scale Jacket'},
 'cycloid_scale_shoes': {'expansion': 'sunstalker',
                         'type': 'skyreef_sanctuary',
                         'name': 'Cycloid Scale Shoes'},
 'cycloid_scale_skirt': {'expansion': 'sunstalker',
                         'type': 'skyreef_sanctuary',
                         'name': 'Cycloid Scale Skirt'},
 'cycloid_scale_sleeves': {'expansion': 'sunstalker',
                           'type': 'skyreef_sanctuary',
                           'name': 'Cycloid Scale Sleeves'},
    'denticle_axe': {
        'expansion': 'sunstalker',
        'type': 'skyreef_sanctuary',
        'name': 'Denticle axe'
    },
    'eye_patch': {
        'expansion': 'sunstalker',
        'type': 'rare_gear',
        'name': 'Eye Patch',
        'keywords': ['item','leather'],
        'desc': 'While you wear this, you are <b>blind</b> in one eye (-1 accuracy), if you are already <b>blind</b>, gain +2 strength for being a badass instead.',
    },
 "gods_string": {'expansion': 'sunstalker',
                  'type': 'rare_gear',
                  'name': "God's String"},
 'ink_blood_bow': {'expansion': 'sunstalker',
                   'type': 'skyreef_sanctuary',
                   'name': 'Ink Blood Bow'},
 'ink_sword': {'expansion': 'sunstalker',
               'type': 'skyreef_sanctuary',
               'name': 'Ink Sword'},
 'prism_mace': {'expansion': 'sunstalker',
                'type': 'sacred_pool',
                'name': 'Prism Mace'},
 'quiver_and_sunstring': {'expansion': 'sunstalker',
                          'type': 'skyreef_sanctuary',
                          'name': 'Quiver and Sunstring'},
 'shadow_saliva_shawl': {'expansion': 'sunstalker',
                         'type': 'skyreef_sanctuary',
                         'name': 'Shadow Saliva Shawl'},
 'skleaver': {'expansion': 'sunstalker',
              'type': 'skyreef_sanctuary',
              'name': 'Skleaver'},
 'sky_harpoon': {'expansion': 'sunstalker',
                 'type': 'skyreef_sanctuary',
                 'name': 'Sky Harpoon'},
 'sun_lure_and_hook': {'expansion': 'sunstalker',
                       'type': 'skyreef_sanctuary',
                       'name': 'Sun Lure and Hook'},
 'sun_vestments': {'expansion': 'sunstalker',
                   'type': 'sacred_pool',
                   'name': 'Sun Vestments'},
 'sunring_bow': {'expansion': 'sunstalker',
                 'type': 'sacred_pool',
                 'name': 'Sunring Bow'},
 'sunshark_arrows': {'expansion': 'sunstalker',
                     'type': 'skyreef_sanctuary',
                     'name': 'Sunshark Arrows'},
 'sunshark_bow': {'expansion': 'sunstalker',
                  'type': 'skyreef_sanctuary',
                  'name': 'Sunshark Bow'},
 'sunspot_dart': {'expansion': 'sunstalker',
                  'type': 'skyreef_sanctuary',
                  'name': 'Sunspot Dart'},
    'sunspot_lantern': {
        'expansion': 'sunstalker',
        'type': 'skyreef_sanctuary',
        'name': 'Sunspot Lantern'
    },
}

white_box_promo = {
    # rare gear
    'bloodskin': {
        'expansion': 'white_box',
        'type': 'rare_gear',
        'name': 'Bloodskin',
    },
    'blue_lantern': {
        'expansion': 'white_box',
        'type': 'rare_gear',
        'name': 'Blue Lantern',
        'keywords': ['item','lantern','order','other'],
        'rules': ['Sentient','Cursed'],
        'desc': '<font class="kdm_font">a</font>: Suffer 2d10 brain damage and reveal HL cards until you reveal the the trap. Put them back in the same order. Limit, once per showdown.',
    },
    'dormant_twilight_cloak': {
        'expansion': 'white_box',
        'type': 'rare_gear',
        'name': 'Dormant Twilight Cloak',
        'keywords': ['item','heavy','order','other'],
        'rules': ['Unique','Irreplaceable','Accessory'],
        'desc': 'Ignore sentient on all gear. You cannot depart with this if you have 3+ understanding. ',
    },
    'speaker_cult_knife': {
        'expansion': 'white_box',
        'type': 'rare_gear',
        'name': 'Speaker Cult Knife',
    },
    'sword_of_silence': {
        'expansion': 'white_box',
        'type': 'rare_gear',
        'name': 'Sword of Silence',
    },

    # promo
    'black_friday_lantern': {
        'attributes': {'evasion': 1},
        'desc': 'on <b>arrival</b> (at the start of the showdown), you may archive this and ambush the monster. limit, once per campaign.',
        'expansion': 'white_box',
        'type': 'promo',
        'name': 'Black Friday Lantern',
        'keywords': ['item', 'lantern', 'other']
    },
    'belt_of_gender_swap': {
        'expansion': 'white_box',
        'type': 'promo',
        'name': 'Belt of Gender Swap',
        'keywords': ['item','jewelry','other'],
        'rules': ['Cursed'],
        'desc': 'While in your gear grid, change to the opposite sex.',
    },
    'blood_plasma_gun': {
        'expansion': 'white_box',
        'type': 'promo',
        'name': 'Blood Plasma Gun'
    },
    'blood_plasma_katana': {
        'expansion': 'white_box',
        'type': 'promo',
        'name': 'Blood Plasma Katana',
    },
    'detective_cap': {
        'expansion': 'white_box',
        'type': 'promo',
        'name': 'Detective Cap',
    },
    'dying_lantern': {
        'expansion': 'white_box',
        'type': 'promo',
        'name': 'Dying Lantern',
        'keywords': ['item','lantern','other'],
        'rules': ['+1 Evasion'],
        'desc': 'You may archive this to gain 1 <b>Skull</b> basic resource and +3 insanity.',
    },
    'nightmare_breast_pump': {'expansion': 'white_box',
                           'type': 'promo',
                           'name': 'Nightmare Breast Pump'},
    'prismatic_lantern': {
        'expansion': 'white_box',
        'type': 'promo',
        'name': 'Prismatic Lantern',
        'keywords': ['item','lantern','other'],
        'rules': ['+1 Movement', 'Unique', 'Irreplaceable'],
        'desc': 'During the showdown, you may archive this and gain 1 permanent affinity of any color.',
    },
 'twilight_revolver': {'expansion': 'white_box',
                       'type': 'promo',
                       'name': 'Twilight Revolver'},
    'twilight_thong': {
        'expansion': 'white_box',
        'type': 'promo',
        'name': 'Twilight Thong',
        'keywords': ['armor','set','rawhide','other'],
        'rules': ['Outfit'],
        'desc': 'Its fabric responds to you; stress causes INTENSE constriction. Do not suffer brain traumas (ignore this if you have destroyed genitals).',
    },
    'vibrant_lantern': {
        'expansion': 'white_box',
        'type': 'promo',
        'name': 'Vibrant Lantern',
        'keywords': ['item','lantern','other'],
        'rules': ['+1 Accuracy'],
        'desc': 'You may archive this to gain 1 <b>Broken Lantern</b> basic resource and 1 survival.',
    },
    'xmaxe': {'expansion': 'white_box', 'type': 'promo', 'name': 'Xmaxe'},

    # gear recipe
    'cloth_leggings': {
        'expansion': 'white_box',
        'type': 'gear_recipe',
        'name': 'Cloth Leggings',
    },
    'hard_breastplate': {
        'expansion': 'white_box',
        'type': 'gear_recipe',
        'name': 'Hard Breastplate',
    },
    "jack_o'_lantern": {
        'expansion': 'white_box',
        'type': 'gear_recipe',
        'name': "Jack O' Lantern",
        'keywords': ['item','consumable','lantern','other'],
        'rules': ['Irreplaceable'],
        'desc': 'During the showdown, if you are, <b>insane</b>, when a survivor dies, gain +10 survival.',
    },
    'tabard': {'expansion': 'white_box',
        'type': 'gear_recipe',
        'name': 'Tabard',
        'keywords': ['item','cloth'],
        'rules': ['Accessory'],
        'desc': 'When you are encouraged, gain +1 insanity if your settlement is <b>Barbaric</b> or gain +1 survival if your settlement is <b>Romantic</b>.',
    },
    'vagabond_armor_set': {'expansion': 'white_box', 'type': 'gear_recipe', 'name': 'Vagabond Armor Set'},

    # ivory carver
    'white_dragon_gauntlets': {
        'expansion': 'white_box',
        'type': 'ivory_carver',
        'name': 'White Dragon Gauntlets'
    },

}

dragon_king = {
    'blast_shield': {'expansion': 'dragon_king',
                  'type': 'dragon_armory',
                  'name': 'Blast Shield'
    },
    'blast_sword': {'expansion': 'dragon_king',
                 'type': 'dragon_armory',
                 'name': 'Blast Sword'
    },
    'blue_power_core': {'expansion': 'dragon_king',
                     'type': 'dragon_armory',
                     'name': 'Blue Power Core'
    },
    'celestial_spear': {
        'expansion': 'dragon_king',
        'type': 'rare_gear',
        'name': 'Celestial Spear',
    },
    'dragon_armor_set': {'expansion': 'dragon_king',
                      'type': 'dragon_armory',
                      'name': 'Dragon Armor Set'},
    'dragon_belt': {'expansion': 'dragon_king',
                 'type': 'dragon_armory',
                 'name': 'Dragon Belt'},
    'dragon_bite_bolt': {'expansion': 'dragon_king',
                      'type': 'dragon_armory',
                      'name': 'Dragon Bite Bolt'},
    'dragon_boots': {'expansion': 'dragon_king',
                  'type': 'dragon_armory',
                  'name': 'Dragon Boots'},
    'dragon_chakram': {'expansion': 'dragon_king',
                    'type': 'dragon_armory',
                    'name': 'Dragon Chakram'},
    'dragon_gloves': {'expansion': 'dragon_king',
                   'type': 'dragon_armory',
                   'name': 'Dragon Gloves'},
    'dragon_mantle': {
        'expansion': 'dragon_king',
        'type': 'dragon_armory',
        'name': 'Dragon Mantle'
    },
    'dragon_vestments': {
        'expansion': 'dragon_king',
        'type': 'rare_gear',
        'name': 'Dragon Vestments'
    },
    'dragonskull_helm': {
        'expansion': 'dragon_king',
        'type': 'dragon_armory',
        'name': 'Dragonskull Helm',
    },
    'hazmat_shield': {
        'expansion': 'dragon_king',
        'type': 'rare_gear',
        'name': 'Hazmat Shield'
    },
    'husk_of_destiny': {
        'expansion': 'dragon_king',
        'type': 'rare_gear',
        'name': 'Husk of Destiny'
    },
    'nuclear_knife': {
        'expansion': 'dragon_king',
        'type': 'dragon_armory',
        'name': 'Nuclear Knife'
    },
    'nuclear_scythe': {
        'expansion': 'dragon_king',
        'type': 'dragon_armory',
        'name': 'Nuclear Scythe'
    },
 'red_power_core': {'expansion': 'dragon_king',
                    'type': 'dragon_armory',
                    'name': 'Red Power Core'},
 'regal_edge': {'expansion': 'dragon_king',
                'type': 'rare_gear',
                'name': 'Regal Edge'},
 'shielded_quiver': {'expansion': 'dragon_king',
                     'type': 'dragon_armory',
                     'name': 'Shielded Quiver'},
 'talon_knife': {'expansion': 'dragon_king',
                 'type': 'dragon_armory',
                 'name': 'Talon Knife'},
}

dbk = {
    'calcified_digging_claw': {'expansion': 'dung_beetle_knight',
                            'type': 'black_harvest',
                            'name': 'Calcified Digging Claw'
    },
    'calcified_greaves': {'expansion': 'dung_beetle_knight',
                       'type': 'black_harvest',
                       'name': 'Calcified Greaves'
    },
    'calcified_juggernaut_blade': {'expansion': 'dung_beetle_knight',
                                'type': 'rare_gear',
                                'name': 'Calcified Juggernaut Blade'
    },
    'calcified_shoulder_pads': {'expansion': 'dung_beetle_knight',
                             'type': 'black_harvest',
                             'name': 'Calcified Shoulder Pads'
    },
    'calcified_zanbato': {'expansion': 'dung_beetle_knight',
                       'type': 'black_harvest',
                       'name': 'Calcified Zanbato'
    },
    'century_greaves': {'expansion': 'dung_beetle_knight',
                     'type': 'wet_resin_crafter',
                     'name': 'Century Greaves'
    },
    'century_shoulder_pads': {
        'expansion': 'dung_beetle_knight',
        'type': 'wet_resin_crafter',
        'name': 'Century Shoulder Pads'
    },
    'dbk_errant_badge': {
        'expansion': 'dung_beetle_knight',
        'type': 'wet_resin_crafter',
        'name': 'DBK Errant Badge'
    },
    'digging_claw': {
        'expansion': 'dung_beetle_knight',
        'type': 'wet_resin_crafter',
        'name': 'Digging Claw'
    },
 'hidden_crimson_jewel': {'expansion': 'dung_beetle_knight',
                          'type': 'rare_gear',
                          'name': 'Hidden Crimson Jewel'},
 'rainbow_wing_belt': {'expansion': 'dung_beetle_knight',
                       'type': 'wet_resin_crafter',
                       'name': 'Rainbow Wing Belt'},
 'regenerating_blade': {'expansion': 'dung_beetle_knight',
                        'type': 'rare_gear',
                        'name': 'Regenerating Blade'},
 'rolling_armor_set': {'expansion': 'dung_beetle_knight',
                       'type': 'wet_resin_crafter',
                       'name': 'Rolling Armor Set'},
 'rubber_bone_harness': {'expansion': 'dung_beetle_knight',
                         'type': 'wet_resin_crafter',
                         'name': 'Rubber Bone Harness'},
 'scarab_circlet': {'expansion': 'dung_beetle_knight',
                    'type': 'wet_resin_crafter',
                    'name': 'Scarab Circlet'},
 'seasoned_monster_meat': {'expansion': 'dung_beetle_knight',
                           'type': 'wet_resin_crafter',
                           'name': 'Seasoned Monster Meat'},
 'the_beetle_bomb': {'expansion': 'dung_beetle_knight',
                     'type': 'wet_resin_crafter',
                     'name': 'The Beetle Bomb'},
 'trash_crown': {'expansion': 'dung_beetle_knight',
                 'type': 'rare_gear',
                 'name': 'Trash Crown'},
}

manhunter = {
    'deathpact': {
        'expansion': 'manhunter',
        'type': 'manhunter_gear',
        'name': 'Deathpact'
    },
 "hunter's_heart": {'expansion': 'manhunter',
                    'type': 'manhunter_gear',
                    'name': "Hunter's Heart"},
 "manhunter's_hat": {'expansion': 'manhunter',
                     'type': 'manhunter_gear',
                     'name': "Manhunter's Hat"},
 'reverberating_lantern': {'expansion': 'manhunter',
                           'type': 'manhunter_gear',
                           'name': 'Reverberating Lantern'},
 'tool_belt': {'expansion': 'manhunter',
               'type': 'manhunter_gear',
               'name': 'Tool Belt'},

}

green_knight = {
    'fetorsaurus': {'expansion': 'green_knight_armor',
                 'type': 'green_knight_armor',
                 'name': 'Fetorsaurus'
    },
    'green_boots': {'expansion': 'green_knight_armor',
                 'type': 'green_knight_armor',
                 'name': 'Green Boots'
    },
    'green_faulds': {'expansion': 'green_knight_armor',
                  'type': 'green_knight_armor',
                  'name': 'Green Faulds'},
 'green_gloves': {'expansion': 'green_knight_armor',
                  'type': 'green_knight_armor',
                  'name': 'Green Gloves'},
 'green_helm': {'expansion': 'green_knight_armor',
                'type': 'green_knight_armor',
                'name': 'Green Helm'},
    'green_plate': {'expansion': 'green_knight_armor',
                 'type': 'green_knight_armor',
                 'name': 'Green Plate'
    },
    'griswaldo': {
        'expansion': 'green_knight_armor',
        'type': 'green_knight_armor',
        'name': 'Griswaldo',
    },

}

unique_no_location = {
}


flower_knight = {
    'flower_knight_badge': {
        'expansion': 'flower_knight',
        'type': 'sense_memory',
        'name': 'Flower Knight Badge'
    },
    'flower_knight_helm': {
        'expansion': 'flower_knight',
        'type': 'rare_gear',
        'name': 'Flower Knight Helm'
    },
 'replica_flower_sword': {'expansion': 'flower_knight',
                          'type': 'rare_gear',
                          'name': 'Replica Flower Sword'},
 'satchel': {'expansion': 'flower_knight',
             'type': 'sense_memory',
             'name': 'Satchel'},
 'sleeping_virus_flower': {'expansion': 'flower_knight',
                           'type': 'rare_gear',
                           'name': 'Sleeping Virus Flower'},
 'vespertine_arrow': {'expansion': 'flower_knight',
                      'type': 'sense_memory',
                      'name': 'Vespertine Arrow'},
 'vespertine_bow': {'expansion': 'flower_knight',
                    'type': 'sense_memory',
                    'name': 'Vespertine Bow'},
 'vespertine_cello': {'expansion': 'flower_knight',
                      'type': 'sense_memory',
                      'name': 'Vespertine Cello'},
 'vespertine_foil': {'expansion': 'flower_knight',
                     'type': 'sense_memory',
                     'name': 'Vespertine Foil'},
}

slenderman = {
    'dark_water_vial': {
        'expansion': 'slenderman',
        'type': 'light_forging',
        'name': 'Dark Water vial',
        'keywords': ['item','consumable','gloomy','fragile'],
    },
    'gloom_bracelets': {
        'expansion': 'slenderman',
        'type': 'light_forging',
        'name': 'Gloom Bracelets',
        'keywords': ['item','jewelry','gloomy','fragile','heavy'],
        'rules': ['Accessory'],
        'desc': 'When you <b>depart</b>, gain +2 insanity. When you suffer a severe arm injury, archive this card.',
    },
    'gloom_coated_arrow': {
        'expansion': 'slenderman',
        'type': 'light_forging',
        'name': 'Gloom-Coated Arrow',
        'rules': ['Ammo - Bow','Cumbersome','Deadly'],
        'keywords': ['item','ammunition','arrow','gloomy'],
    },
    'gloom_cream': {
        'expansion': 'slenderman',
        'type': 'light_forging',
        'name': 'Gloom Cream',
        'keywords': ['item','consumable','balm','gloomy','stinky','other'],
    },
    'gloom_hammer': {
        'expansion': 'slenderman',
        'type': 'light_forging',
        'name': 'Gloom Hammer',
        'rules': ['Unique','Sentient','Reach 2','Deadly'],
        'keywords': ['weapon','melee','club','two-handed','gloomy','other'],
    },
    'gloom_katana': {
        'expansion': 'slenderman',
        'type': 'light_forging',
        'name': 'Gloom Katana',
        'keywords': ['weapon','melee','katana','two-handed','finesse','gloomy','other'],
        'desc': "Your insanity is added to this weapon's strength. When Gloom Sheath is right of this in your gear grid, Gloom Katana gains <b>Savage</b>.",
    },
    'gloom_mehndi': {
        'expansion': 'slenderman',
        'type': 'light_forging',
        'name': 'Gloom Mehndi',
        'keywords': ['item','gloomy','soluble'],
    },
    'gloom_sheath': {
        'expansion': 'slenderman',
        'type': 'light_forging',
        'name': 'Gloom Sheath',
        'keywords': ['item','gloomy','other'],
        'rules': ['Block 1'],
    },
    'raptor_worm_collar': {
        'expansion': 'slenderman',
        'type': 'light_forging',
        'name': 'Raptor-Worm Collar',
        'keywords': ['item','jewelry','gloomy'],
        'desc': 'You may <b>encourage</b> without spending survival. When you <b>encourage</b> a survivor, they suffer 2 brain damage.',
    },
    'slender_ovule': {
        'expansion': 'slenderman',
        'type': 'light_forging',
        'name': 'Slender Ovule',
        'keywords': ['item','jewelry','gloomy','other'],
        'rules': ['Unique'],
        'desc': 'When you <b>depart</b>, gain +3 insanity.',
    },
}


lion_knight = {
 'hideous_disguise': {'expansion': 'lion_knight',
                      'type': 'rare_gear',
                      'name': 'Hideous Disguise'},
 "lion_knights_left_claw": {'expansion': 'lion_knight',
                             'type': 'rare_gear',
                             'name': "Lion Knight's Left Claw"},
 "lion_knights_right_claw": {'expansion': 'lion_knight',
                              'type': 'rare_gear',
                              'name': "Lion Knight's Right claw"},
 'lion_knight_badge': {'expansion': 'lion_knight',
                       'type': 'rare_gear',
                       'name': 'Lion Knight Badge'},
}


