core_resources = {

    # basic resources
    '_question_marks': {
        'type': 'basic_resources',
        'name': '???',
        'keywords': ['organ', 'hide', 'bone','consumable'],
        'desc': 'You have no idea what monster bit this is. Can be used as a bone, organ, or hide!',
    },
    'broken_lantern': {
        'type': 'basic_resources',
        'name': 'Broken Lantern',
        'keywords': ['scrap'],
        'desc': '<i>Remains of an extinguished lantern.</i>',
    },
    'love_juice': {
       'type': 'basic_resources',
       'name': 'Love Juice',
       'keywords': ['organ','consumable']
    },
    'monster_bone': {
        'type': 'basic_resources',
        'name': 'Monster Bone',
        'keywords': ['bone']
    },
    'monster_hide': {
        'type': 'basic_resources',
        'name': 'Monster Hide',
        'keywords': ['hide'],
        'desc': '<i>The skin of a beast.</i>',
    },
    'monster_organ': {
        'type': 'basic_resources',
        'name': 'Monster Organ',
        'keywords': ['organ']
    },
    'scrap': {
        'type': 'basic_resources',
        'name': 'Scrap',
        'keywords': ['scrap']
    },
    'skull': {
        'type': 'basic_resources',
        'name': 'Skull',
        'keywords': ['bone'],
        'desc': 'When you gain this, a survivor of your choice gains +1 insanity.',
    },

    # strange resources
    'black_lichen': {
        'desc': 'Malleable, pungent and attractive.<br/>You may <b>consume</b> this. If you do, your lips turn grey, your hair whitens, and you become infertile. Gain +1 courage, +1 understanding and suffer the <b>destroyed genitals</b> severe waist injury.',
        'keywords': ['bone','organ','hide','consumable','other'],
        'type': 'strange_resources',
        'name': 'Black Lichen',
        'keywords': ['bone', 'organ', 'hide']
    },
    'cocoon_membrane': {
        'desc': 'Thin copper hairs permeate this jellylike substance.<br/>Lanterns are repelled by the copper hairs, their light bending to avoid them.',
        'keywords': ['organ', 'other'],
        'type': 'strange_resources',
        'name': 'Cocoon Membrane',
        'keywords': ['organ']
    },
    'elder_cat_teeth': {
        'type': 'strange_resources',
        'name': 'Elder Cat Teeth',
        'keywords': ['bone'],
        'desc': 'As sharp as they are strange.',
    },
    'fresh_acanthus': {
        'type': 'strange_resources',
        'name': 'Fresh Acanthus',
        'keywords': ['herb'],
        'desc': 'Archive this to fully heal 1 hit location, including injury levels and armor points.',
    },
    'iron': {
        'type': 'strange_resources',
        'name': 'Iron',
        'keywords': ['scrap'],
        'desc': 'Harder than bone.',
    },
    'lantern_tube': {
        'desc': "A fleshy, muscle-lined tube.<br/>When you gain this, roll 1d10. On a 6+ you find something stuck inside! Add <b>1 Broken Lantern</b> basic resource to the settlement's storage.",
        'type': 'strange_resources',
        'name': 'Lantern Tube',
        'keywords': ['organ', 'scrap']
    },
    'leather': {
        'type': 'strange_resources',
        'name': 'Leather',
        'keywords': ['hide'],
        'desc': 'Never goes out of style.',
    },
    'legendary_horns': {
        'type': 'strange_resources',
        'name': 'Legendary Horns',
        'keywords': ['bone', 'scrap'],
        'desc': 'Holding them fills you with power.',
    },
    'perfect_crucible': {
        'type': 'strange_resources',
        'name': 'Perfect Crucible',
        'keywords': ['iron'],
        'desc': 'When you craft with Perfect Crucible, an ancient bacteria is released into the air. Suffer -1d10 population and archive this card.',
    },
    'phoenix_crest': {
        'type': 'strange_resources',
        'name': 'Phoenix Crest',
        'keywords': ['organ'],
        'desc': 'Firm and supple.',
    },
    'second_heart': {
        'type': 'strange_resources',
        'name': 'Second Heart',
        'keywords': ['organ', 'bone'],
        'desc': 'It still tries to bite you.',
    },

    # screaming antelope
    'beast_steak': {
        'type': 'screaming_antelope_resources',
        'name': 'Beast Steak',
        'keywords': ['organ']
    },
    'bladder': {'consumable': True,
             'type': 'screaming_antelope_resources',
             'name': 'Bladder',
             'keywords': ['organ']},
    'large_flat_tooth': {'type': 'screaming_antelope_resources',
                      'name': 'Large Flat Tooth',
                      'keywords': ['bone']},
    'muscly_gums': {'consumable': True,
                 'type': 'screaming_antelope_resources',
                 'name': 'Muscly Gums',
                 'keywords': ['organ']},
    'pelt': {
        'type': 'screaming_antelope_resources',
        'name': 'Pelt',
        'keywords': ['hide']
    },
 'screaming_brain': {'consumable': True,
                     'type': 'screaming_antelope_resources',
                     'name': 'Screaming Brain',
                     'keywords': ['organ']},
 'shank_bone': {'type': 'screaming_antelope_resources',
                'name': 'Shank Bone',
                'keywords': ['bone']},
 'spiral_horn': {'type': 'screaming_antelope_resources',
                 'name': 'Spiral Horn',
                 'keywords': ['bone']},

    # phoenix
    'bird_beak': {
        'type': 'phoenix_resources',
        'name': 'Bird Beak',
        'keywords': ['bone']
    },
 'black_skull': {'type': 'phoenix_resources',
                 'name': 'Black Skull',
                 'keywords': ['scrap', 'bone']},
 'hollow_wing_bones': {'type': 'phoenix_resources',
                       'name': 'Hollow Wing Bones',
                       'keywords': ['bone']},
    'muculent_droppings': {'type': 'phoenix_resources',
                        'name': 'Muculent Droppings',
                        'keywords': ['organ']
    },
 'phoenix_eye': {'type': 'phoenix_resources',
                 'name': 'Phoenix Eye',
                 'keywords': ['organ', 'scrap']},
 'phoenix_finger': {'type': 'phoenix_resources',
                    'name': 'Phoenix Finger',
                    'keywords': ['bone']},
 'phoenix_whisker': {'type': 'phoenix_resources',
                     'name': 'Phoenix Whisker',
                     'keywords': ['hide']},
 'pustules': {'consumable': True,
              'type': 'phoenix_resources',
              'name': 'Pustules',
              'keywords': ['organ']},
 'rainbow_droppings': {'consumable': True,
                       'type': 'phoenix_resources',
                       'name': 'Rainbow Droppings',
                       'keywords': ['organ']},
 'shimmering_halo': {'type': 'phoenix_resources',
                     'name': 'Shimmering Halo',
                     'keywords': ['organ']},
 'small_feathers': {'type': 'phoenix_resources',
                    'name': 'Small Feathers',
                    'keywords': ['hide']},
    'small_hand_parasites': {
        'type': 'phoenix_resources',
        'name': 'Small Hand Parasites',
        'keywords': ['organ']
    },
    'tail_feathers': {
        'type': 'phoenix_resources',
        'name': 'Tail Feathers',
        'keywords': ['hide']
    },
    'wishbone': {
        'type': 'phoenix_resources',
        'name': 'Wishbone',
        'keywords': ['bone']
    },

    # white lion
    'curious_hand': {
        'type': 'white_lion_resources',
        'name': 'Curious Hand',
        'keywords': ['hide'],
        'desc': 'When you gain this, a random survivor gains +1 insanity.<br/><i>Holding this fills you with sadness.</i>',
    },
    'eye_of_cat': {
        'type': 'white_lion_resources',
        'name': 'Eye of Cat',
        'keywords': ['organ','consumable'],
        'desc': '<i>A perfectly preserved eye.</i>',
    },
    'golden_whiskers': {
        'type': 'white_lion_resources',
        'name': 'Golden Whiskers',
        'keywords': ['organ'],
        'desc': '<i>These whiskers are tough!</i>',
    },
    'great_cat_bones': {
        'type': 'white_lion_resources',
        'name': 'Great Cat Bones',
        'keywords': ['bone'],
        'desc': 'Strong and surprisingly light.',
    },
    'lion_claw': {
        'type': 'white_lion_resources',
        'name': 'Lion Claw',
        'keywords': ['bone'],
        'desc': '<i>A razor-sharp, retractable claw.</i>',
    },
    'lion_tail': {
        'type': 'white_lion_resources',
        'name': 'Lion Tail',
        'keywords': ['hide'],
        'desc': "<i>It's surprisingly heavy.</i>",
    },
    'lion_testes': {
        'type': 'white_lion_resources',
        'name': 'Lion Testes',
        'keywords': ['organ','consumable'],
        'desc': '<i>A hefty pair of nuts.</i>',
    },
    'shimmering_mane': {
        'type': 'white_lion_resources',
        'name': 'Shimmering Mane',
        'keywords': ['hide'],
        'desc': 'Archive this to gain 2 basic hide resources.<br/><i>It shimmers in the lantern light.</i>',
    },
    'sinew': {
        'type': 'white_lion_resources',
        'name': 'Sinew',
        'keywords': ['organ'],
    },
    'white_fur': {
        'type': 'white_lion_resources',
        'name': 'White Fur',
        'keywords': ['hide'],
        'desc': '<i>Luxurious and soft to the touch.</i>',
    },
}


vermin = {
    'crab_spider': {
        'type': 'vermin',
        'name': 'Crab Spider',
        'desc': '<b>Consume:</b> Archive this and gain +3 survival.',
        'keywords': ['hide','vermin','consumable'],
    },
    'cyclops_fly': {
        'type': 'vermin',
        'name': 'Cyclops Fly',
        'desc': '<b>Consume:</b> Archive this and roll 1d10.',
        'keywords': ['vermin','consumable'],
    },
    'hissing_cockroach': {
        'type': 'vermin',
        'name': 'Hissing Cockroach',
        'keywords': ['vermin','consumable'],
        'desc': '<b>Consume:</b> Archive this to lose all survival and gain 2d10 insanity.<br/>If you are insane, you must consume this.',
    },
    'lonely_ant': {
        'type': 'vermin',
        'name': 'Lonely Ant',
        'keywords': ['vermin','consumable'],
        'desc': '<b>Consume:</b> Archive this to swap your insanity and survival values.',
    },
    'nightmare_tick': {
        'type': 'vermin',
        'name': 'Nightmare Tick',
        'keywords': ['vermin','consumable'],
        'desc': '<b>Consume:</b> Archive this and roll 1d10.',
    },
    'sword_beetle': {
        'type': 'vermin',
        'name': 'Sword Beetle',
        'desc': '<b>Consume:</b> Archive this and roll 1d10.',
        'keywords': ['vermin','consumable'],
    },
}


expansions = {


    #gorm
    'acid_gland': {'expansion': 'gorm',
                'type': 'gorm_resources',
                'name': 'Acid Gland',
                'keywords': ['organ']},
    'active_thyroid': {
        'expansion': 'gorm',
        'type': 'strange_resources',
        'name': 'Active Thyroid',
        'keywords': ['organ','consumable'],
    },
 'dense_bone': {'expansion': 'gorm',
                'type': 'gorm_resources',
                'name': 'Dense Bone',
                'keywords': ['bone']},
 'gorm_brain': {'expansion': 'gorm',
                'type': 'gorm_resources',
                'name': 'Gorm Brain',
                'keywords': ['organ']},
    'gormite': {
        'expansion': 'gorm',
        'type': 'strange_resources',
        'name': 'Gormite',
        'keywords': ['scrap', 'iron'],
        'desc': 'The toughest stuff known to man.',
    },
 'handed_skull': {'expansion': 'gorm',
                  'type': 'gorm_resources',
                  'name': 'Handed Skull',
                  'keywords': ['bone']},
 'jiggling_lard': {'expansion': 'gorm',
                   'type': 'gorm_resources',
                   'name': 'Jiggling Lard',
                   'keywords': ['hide', 'organ']},
 'mammoth_hand': {'expansion': 'gorm',
                  'type': 'gorm_resources',
                  'name': 'Mammoth Hand',
                  'keywords': ['bone', 'hide', 'organ']},
 'meaty_rib': {'expansion': 'gorm',
               'type': 'gorm_resources',
               'name': 'Meaty Rib',
               'keywords': ['bone', 'organ']},
 'milky_eye': {'expansion': 'gorm',
               'type': 'gorm_resources',
               'name': 'Milky Eye',
               'keywords': ['organ']},
    'pure_bulb': {
        'expansion': 'gorm',
        'type': 'strange_resources',
        'name': 'Pure Bulb',
        'keywords': ['organ'],
        'desc': "Don't stare at it.",
    },
    'stomach_lining': {
        'expansion': 'gorm',
        'type': 'strange_resources',
        'name': 'Stomach Lining',
        'keywords': ['organ'],
        'desc': 'Steadily expands and contracts.',
    },
 'stout_heart': {'expansion': 'gorm',
                 'type': 'gorm_resources',
                 'name': 'Stout Heart',
                 'keywords': ['organ']},
 'stout_hide': {'expansion': 'gorm',
                'type': 'gorm_resources',
                'name': 'Stout Hide',
                'keywords': ['hide']},
 'stout_kidney': {'consumable': True,
                  'expansion': 'gorm',
                  'type': 'gorm_resources',
                  'name': 'Stout Kidney',
                  'keywords': ['organ']},
 'stout_vertebrae': {'expansion': 'gorm',
                     'type': 'gorm_resources',
                     'name': 'Stout Vertebrae',
                     'keywords': ['bone']},


    # spidicules
    'arachnid_heart': {'expansion': 'spidicules',
                    'type': 'spidicules_resources',
                    'name': 'Arachnid Heart',
                    'keywords': ['organ']},
 'chitin': {'expansion': 'spidicules',
            'type': 'spidicules_resources',
            'name': 'Chitin',
            'keywords': ['hide']},
 'exoskeleton': {'expansion': 'spidicules',
                 'type': 'spidicules_resources',
                 'name': 'Exoskeleton',
                 'keywords': ['hide']},
 'eyeballs': {'expansion': 'spidicules',
              'type': 'spidicules_resources',
              'name': 'Eyeballs',
              'keywords': ['organ']},
 'large_appendage': {'expansion': 'spidicules',
                     'type': 'spidicules_resources',
                     'name': 'Large Appendage',
                     'keywords': ['bone']},
    'serrated_fangs': {
        'endeavors': ['serrated_fangs_razor_pushups'],
        'expansion': 'spidicules',
        'type': 'spidicules_resources',
        'name': 'Serrated Fangs',
        'keywords': ['bone'],
    },
    'silken_nervous_system': {
        'expansion': 'spidicules',
        'type': 'strange_resources',
        'name': 'Silken Nervous System',
        'keywords': ['organ'],
        'desc': 'Separates into tiny golden threads.',
    },
 'small_appendages': {'expansion': 'spidicules',
                      'type': 'spidicules_resources',
                      'name': 'Small Appendages',
                      'keywords': ['hide']},
 'spinnerets': {'expansion': 'spidicules',
                'type': 'spidicules_resources',
                'name': 'Spinnerets',
                'keywords': ['organ', 'scrap']},
 'stomach': {'expansion': 'spidicules',
             'type': 'spidicules_resources',
             'name': 'Stomach',
             'keywords': ['organ']},
 'thick_web_silk': {'expansion': 'spidicules',
                    'type': 'spidicules_resources',
                    'name': 'Thick Web Silk',
                    'keywords': ['hide']},
 'unlaid_eggs': {'expansion': 'spidicules',
                 'type': 'spidicules_resources',
                 'name': 'Unlaid Eggs',
                 'keywords': ['organ']},
 'venom_sac': {'expansion': 'spidicules',
               'type': 'spidicules_resources',
               'name': 'Venom Sac',
               'keywords': ['organ']},
    'web_silk': {
        'expansion': 'spidicules',
        'type': 'strange_resources',
        'name': 'Web Silk',
        'keywords': ['silk'],
        'desc': 'Impossible to tear.',
    },


    # dung_beetle_knight dbk

    'beetle_horn': {'expansion': 'dung_beetle_knight',
                 'type': 'dung_beetle_knight_resources',
                 'name': 'Beetle Horn',
                 'keywords': ['bone']},
 'century_fingernails': {'expansion': 'dung_beetle_knight',
                         'type': 'dung_beetle_knight_resources',
                         'name': 'Century Fingernails',
                         'keywords': ['bone']},
 'century_shell': {'expansion': 'dung_beetle_knight',
                   'type': 'dung_beetle_knight_resources',
                   'name': 'Century Shell',
                   'keywords': ['hide', 'scrap']},
 'compound_eye': {'expansion': 'dung_beetle_knight',
                  'type': 'dung_beetle_knight_resources',
                  'name': 'Compound Eye',
                  'keywords': ['organ']},
 'elytra': {'expansion': 'dung_beetle_knight',
            'type': 'dung_beetle_knight_resources',
            'name': 'Elytra',
            'keywords': ['bone', 'hide', 'organ']},
    'preserved_caustic_dung': {
        'expansion': 'dung_beetle_knight',
        'type': 'strange_resources',
        'name': 'Preserved Caustic Dung',
        'keywords': ['organ','consumable','dung']
    },
 'scarab_shell': {'expansion': 'dung_beetle_knight',
                  'type': 'dung_beetle_knight_resources',
                  'name': 'Scarab Shell',
                  'keywords': ['hide']},
 'scarab_wing': {'expansion': 'dung_beetle_knight',
                 'type': 'dung_beetle_knight_resources',
                 'name': 'Scarab Wing',
                 'keywords': ['organ']},
    'scell': {
        'expansion': 'dung_beetle_knight',
        'type': 'strange_resources',
        'name': 'Scell',
        'keywords': ['organ','consumable'],
    },
 'underplate_fungus': {'expansion': 'dung_beetle_knight',
                       'type': 'dung_beetle_knight_resources',
                       'name': 'Underplate Fungus',
                       'keywords': ['hide']},


    # sunstalker
    '1000_year_sunspot': {
        'expansion': 'sunstalker',
        'type': 'strange_resources',
        'name': '1,000 Year Sunspot',
        'keywords': ['bone', 'organ'],
        'desc': 'When you craft with this, nominate a survivor. They suffer the <b>blind</b> severe injury from working with this resource.',
    },
    '3000_year_sunspot': {
        'expansion': 'sunstalker',
        'type': 'strange_resources',
        'name': '3,000 Year Sunspot',
        'keywords': ['bone', 'organ', 'scrap'],
        'desc': 'When you craft with this, nominate a survivor and roll 1d10. On a 5+ they get a terrible headache and die.',
    },
 'black_lens': {'expansion': 'sunstalker',
                'type': 'sunstalker_resources',
                'name': 'Black Lens',
                'keywords': ['organ']},
 'brain_root': {'expansion': 'sunstalker',
                'type': 'sunstalker_resources',
                'name': 'Brain Root',
                'keywords': ['organ']},
    'bugfish': {
        'expansion': 'sunstalker',
        'type': 'strange_resources',
        'name': 'Bugfish',
        'keywords': ['fish','organ'],
        'desc': '<b>Consume:</b> Gain +2 survival. There is something in its belly! Gain 1 random vermin and <b>consume</b> it immediately. Archive this card.',
    },
 'cycloid_scales': {'expansion': 'sunstalker',
                    'type': 'sunstalker_resources',
                    'name': 'Cycloid Scales',
                    'keywords': ['hide']},
 'fertility_tentacle': {'expansion': 'sunstalker',
                        'type': 'sunstalker_resources',
                        'name': 'Fertility Tentacle',
                        'keywords': ['organ']},
 'hagfish': {'expansion': 'sunstalker',
             'type': 'strange_resources',
             'name': 'Hagfish',
             'keywords': ['bone', 'hide']},
 'huge_sunteeth': {'expansion': 'sunstalker',
                   'type': 'sunstalker_resources',
                   'name': 'Huge Sunteeth',
                   'keywords': ['bone']},
 'inner_shadow_skin': {'expansion': 'sunstalker',
                       'type': 'sunstalker_resources',
                       'name': 'Inner Shadow Skin',
                       'keywords': ['hide']},
 'jowls': {'expansion': 'sunstalker',
           'type': 'strange_resources',
           'name': 'Jowls',
           'keywords': ['scrap']},
 'prismatic_gills': {'expansion': 'sunstalker',
                     'type': 'sunstalker_resources',
                     'name': 'Prismatic Gills',
                     'keywords': ['organ']},
    'salt': {
        'expansion': 'sunstalker',
        'type': 'strange_resources',
        'name': 'Salt',
        'desc': "You may add this to any cooking recipe to gain +1 permanent strength in addition to the recipe's listed benefits.<br/><i>When exposed to lantern light it evaporates, forming a crust</i>.",
    },
 'shadow_ink_gland': {'expansion': 'sunstalker',
                      'type': 'sunstalker_resources',
                      'name': 'Shadow Ink Gland',
                      'keywords': ['organ']},
 'shadow_tentacles': {'expansion': 'sunstalker',
                      'type': 'sunstalker_resources',
                      'name': 'Shadow Tentacles',
                      'keywords': ['organ', 'hide']},
 'shark_tongue': {'expansion': 'sunstalker',
                  'type': 'sunstalker_resources',
                  'name': 'Shark Tongue',
                  'keywords': ['organ']},
 'small_sunteeth': {'expansion': 'sunstalker',
                    'type': 'sunstalker_resources',
                    'name': 'Small Sunteeth',
                    'keywords': ['bone']},
 'stink_lung': {'expansion': 'sunstalker',
                'type': 'sunstalker_resources',
                'name': 'Stink Lung',
                'keywords': ['organ']},
    'sunstones': {
        'expansion': 'sunstalker',
        'type': 'strange_resources',
        'name': 'Sunstones',
        'misspellings': ['Sun Stones'],
        'keywords': ['bone'],
        'desc': 'Small and warm.',
    },
 'sunshark_blubber': {'expansion': 'sunstalker',
                      'type': 'sunstalker_resources',
                      'name': 'Sunshark Blubber',
                      'keywords': ['organ']},
 'sunshark_bone': {'expansion': 'sunstalker',
                   'type': 'sunstalker_resources',
                   'name': 'Sunshark Bone',
                   'keywords': ['bone']},
    'sunshark_fin': {
        'expansion': 'sunstalker',
        'type': 'sunstalker_resources',
        'name': 'Sunshark Fin',
        'keywords': ['bone', 'hide'],
    },


    # lonely_tree
    'blistering_plasma_fruit': {
        'expansion': 'lonely_tree',
        'type': 'strange_resources',
        'name': 'Blistering Plasma Fruit',
        'keywords': ['organ','consumable'],
    },
    'drifting_dream_fruit': {
        'expansion': 'lonely_tree',
        'type': 'strange_resources',
        'name': 'Drifting Dream Fruit',
        'keywords': ['consumable'],
    },
    'jagged_marrow_fruit': {
        'expansion': 'lonely_tree',
        'type': 'strange_resources',
        'name': 'Jagged Marrow Fruit',
        'keywords': ['bone', 'scrap','consumable']
    },
    'lonely_fruit': {
        'expansion': 'lonely_tree',
        'type': 'strange_resources',
        'name': 'Lonely Fruit',
        'keywords': ['consumable'],
    },
    'porous_flesh_fruit': {
        'expansion': 'lonely_tree',
        'type': 'strange_resources',
        'name': 'Porous Flesh Fruit',
        'keywords': ['hide','consumable'],
    },


    #dragon_king
    'cabled_vein': {'expansion': 'dragon_king',
                 'type': 'dragon_king_resources',
                 'name': 'Cabled Vein',
        'keywords': ['organ']
    },
 'dragon_iron': {'expansion': 'dragon_king',
                 'type': 'dragon_king_resources',
                 'name': 'Dragon Iron',
                 'keywords': ['scrap']},
 'hardened_ribs': {'expansion': 'dragon_king',
                   'type': 'dragon_king_resources',
                   'name': 'Hardened Ribs',
                   'keywords': ['bone']},
 'horn_fragment': {'expansion': 'dragon_king',
                   'type': 'dragon_king_resources',
                   'name': 'Horn Fragment',
                   'keywords': ['bone']},
 'husk': {'expansion': 'dragon_king',
          'type': 'dragon_king_resources',
          'name': 'Husk',
          'keywords': ['hide']},
 "kings_claws": {'expansion': 'dragon_king',
                  'type': 'dragon_king_resources',
                  'name': "King's Claws",
                  'keywords': ['bone']},
 "kings_tongue": {'expansion': 'dragon_king',
                   'type': 'dragon_king_resources',
                   'name': "King's Tongue",
                   'keywords': ['hide']},
    'pituitary_gland': {
        'expansion': 'dragon_king',
        'type': 'strange_resources',
        'name': 'Pituitary Gland',
        'keywords': ['organ','consumable'],
        'desc': '<b>Consume:</b> Archive this and roll 1d10. On a 4+, gain +1 permanent strength. Otherwise, you grow to giant size and die.',
    },
    'radiant_heart': {
        'expansion': 'dragon_king',
        'type': 'strange_resources',
        'name': 'Radiant Heart',
        'keywords': ['organ'],
        'desc': 'When you gain this resource, roll 1d10. On a 3+ you burst into flames and die.',
    },
 'radioactive_dung': {'expansion': 'dragon_king',
                      'type': 'dragon_king_resources',
                      'name': 'Radioactive Dung',
                      'keywords': ['organ', 'scrap']},
    'shining_liver': {
        'expansion': 'dragon_king',
        'type': 'strange_resources',
        'name': 'Shining Liver',
        'keywords': ['organ'],
    },
    'veined_wing': {
        'expansion': 'dragon_king',
        'type': 'dragon_king_resources',
        'name': 'Veined Wing',
        'keywords': ['hide'],
    },

    # lion_god
    'canopic_jar': {
        'expansion': 'lion_god',
        'type': 'strange_resources',
        'name': 'Canopic Jar',
        'keywords': ['organ', 'scrap'],
    },
    'old_blue_box': {
        'expansion': 'lion_god',
        'type': 'strange_resources',
        'name': 'Old Blue Box',
        'keywords': ['scrap'],
    },
    'sarcophagus': {
        'expansion': 'lion_god',
        'type': 'strange_resources',
        'name': 'Sarcophagus',
        'keywords': ['iron']
    },
    'silver_urn': {
        'expansion': 'lion_god',
        'type': 'strange_resources',
        'name': 'Silver urn',
        'keywords': ['bone', 'scrap'],
    },
    'triptych': {
        'expansion': 'lion_god',
        'type': 'strange_resources',
        'name': 'Triptych',
        'keywords': ['hide', 'scrap'],
    },


    # manhunter
    'crimson_vial': {
        'expansion': 'manhunter',
        'type': 'strange_resources',
        'name': 'Crimson Vial',
        'keywords': ['iron', 'consumable'],
        'desc': 'You may <b>consume</b> and archive this to remove all bleeding tokens and any severe injury of your choice.',
    },
    'red_vial': {
        'expansion': 'manhunter',
        'type': 'strange_resources',
        'name': 'Red Vial',
        'desc': 'You may <b>consume</b> and archive this to remove 2 bleeding tokens and gain +1 survival.',
        'keywords': ['consumable'],
    },

    # slenderman
    'crystal_sword_mold': {
        'expansion': 'slenderman',
        'type': 'strange_resources',
        'name': 'Crystal Sword Mold',
        'keywords': ['scrap','iron'],
    },
    'dark_water': {
        'expansion': 'slenderman',
        'type': 'strange_resources',
        'name': 'Dark Water',
        'keywords': ['other','consumable'],
        'desc': "You may <b>consume</b> and archive this to remove all your disorders, then gain a random disorder.",
    },

    # flower knight
    'lantern_bloom': {
        'expansion': 'flower_knight',
        'type': 'flower_knight_resources',
        'name': 'Lantern Bloom',
        'keywords': ['flower','hide','perishable']
    },
    'lantern_bud': {
        'expansion': 'flower_knight',
        'type': 'flower_knight_resources',
        'name': 'Lantern Bud',
        'keywords': ['flower','scrap','perishable'],
    },
    'osseous_bloom': {
        'expansion': 'flower_knight',
        'type': 'flower_knight_resources',
        'name': 'Osseous Bloom',
        'keywords': ['flower','bone','perishable']
    },
    'sighing_bloom': {
        'expansion': 'flower_knight',
        'type': 'flower_knight_resources',
        'name': 'Sighing Bloom',
        'keywords': ['flower','organ','perishable']
    },
    'warbling_bloom': {
        'expansion': 'flower_knight',
        'type': 'flower_knight_resources',
        'name': 'Warbling Bloom',
        'keywords': ['flower','hide','perishable']
    },

}


