preferences_dict = {
    "beta": {
        "type": "General",
        "desc": "Enable beta features of the Manager?",
        "affirmative": "Enable",
        "negative": "Disable",
        "patron_level": 2,
    },
    "preserve_sessions": {
        "type": "General",
        "desc": "Preserve Sessions?",
        "affirmative": "Keep me logged in",
        "negative": "Remove sessions after 24 hours",
        "patron_level": 0,
    },
    "random_names_for_unnamed_assets": {
        "type": "General",
        "desc": "Choose random names for Settlements/Survivors without names?",
        "affirmative": "Choose randomly",
        "negative": "Use 'Unknown' and 'Anonymous'",
        "patron_level": 0,
    },
    "apply_new_survivor_buffs": {
        "type": "Automation",
        "desc": "Automatically apply settlement bonuses to new, newborn and current survivors where appropriate?",
        "affirmative": "Automatically apply",
        "negative": "Do not apply",
        "patron_level": 0,
    },
    "apply_weapon_specialization": {
        "type": "Automation",
        "desc": "Automatically add weapon specializations if Innovations include the mastery?",
        "affirmative": "Add",
        "negative": "Do Not Add",
        "patron_level": 0,
    },
    "show_endeavor_token_controls": {
        "type": "Campaign Summary",
        "desc": "Show Endeavor Token controls on Campaign Summary view?",
        "affirmative": "Show controls",
        "negative": "Hide controls",
        "patron_level": 0,
    },
#    "update_timeline": {
#        "type": "Automation",
#        "desc": "Automatically Update Timeline with Milestone Story Events?",
#        "affirmative": "Update settlement timelines when milestone conditions are met",
#        "negative": "Do not automatically update settlement timelines",
#        "patron_level": 0,
#    },
    "show_epithet_controls": {
        "type": "Survivor Sheet",
        "desc": "Use survivor epithets?",
        "affirmative": "Show controls on Survivor Sheets",
        "negative": "Hide controls and survivor epithets on Survivor Sheets",
        "patron_level": 0,
    },
    "show_remove_button": {
        "type": "General",
        "desc": "Show controls for removing Settlements and Survivors?",
        "affirmative": "Show controls on Settlement and Survivor Sheets",
        "negative": "Hide controls on Settlement and Survivor Sheets",
        "patron_level": 0,
    },
}
